set(ffmpeg_src /home/martin/src/ffmpeg-6.1.2/)
set(libavutil_asm ${ffmpeg_src}/libavutil/x86)
set(libavutil_c ${ffmpeg_src}/libavutil)
set(libavcodec_asm ${ffmpeg_src}/libavcodec/x86)
set(libavcodec_c ${ffmpeg_src}/libavcodec)
set(libavformat_c ${ffmpeg_src}/libavformat)
set(libavdevice_c ${ffmpeg_src}/libavdevice)


set(avutil_asm
        ${libavutil_asm}/fixed_dsp.asm
        ${libavutil_asm}/tx_float.asm
        ${libavutil_asm}/float_dsp.asm
        ${libavutil_asm}/imgutils.asm
        ${libavutil_asm}/lls.asm
        ${libavutil_asm}/cpuid.asm
)

set(avcodec_asm
        ${libavcodec_asm}/videodsp.asm
        ${libavcodec_asm}/h264_idct_10bit.asm
        ${libavcodec_asm}/vp9intrapred.asm
        ${libavcodec_asm}/h264_weight.asm
        ${libavcodec_asm}/vp9lpf.asm
        ${libavcodec_asm}/h264_intrapred_10bit.asm
        ${libavcodec_asm}/fpel.asm
        ${libavcodec_asm}/h264_deblock_10bit.asm
        ${libavcodec_asm}/vp9lpf_16bpp.asm
        ${libavcodec_asm}/h264_chromamc.asm
        ${libavcodec_asm}/vp9itxfm.asm
        ${libavcodec_asm}/vp9mc_16bpp.asm
        ${libavcodec_asm}/h264_qpel_10bit.asm
        ${libavcodec_asm}/vp9mc.asm
        ${libavcodec_asm}/qpel.asm
        ${libavcodec_asm}/h264_intrapred.asm
        ${libavcodec_asm}/h264_weight_10bit.asm
        ${libavcodec_asm}/vp9intrapred_16bpp.asm
        ${libavcodec_asm}/vp9itxfm_16bpp.asm
        ${libavcodec_asm}/h264_qpel_8bit.asm
        ${libavcodec_asm}/h264_deblock.asm
        ${libavcodec_asm}/h264_idct.asm
        ${libavcodec_asm}/h264_chromamc_10bit.asm
)

set(avutil_c
        ${libavutil_c}/stereo3d.c
        ${libavutil_c}/lfg.c
        ${libavutil_c}/executor.c
        ${libavutil_c}/xtea.c
        ${libavutil_c}/buffer.c
        ${libavutil_c}/pixelutils.c
        ${libavutil_c}/parseutils.c
        ${libavutil_c}/version.c
        ${libavutil_c}/ripemd.c
        ${libavutil_c}/adler32.c
        ${libavutil_c}/cpu.c
        ${libavutil_c}/file.c
        ${libavutil_c}/random_seed.c
        ${libavutil_c}/md5.c
        ${libavutil_c}/audio_fifo.c
        ${libavutil_c}/hdr_dynamic_vivid_metadata.c
        ${libavutil_c}/mathematics.c
        ${libavutil_c}/tea.c
        ${libavutil_c}/murmur3.c
        ${libavutil_c}/intmath.c
        ${libavutil_c}/fixed_dsp.c
        ${libavutil_c}/tx_double.c
        ${libavutil_c}/downmix_info.c
        ${libavutil_c}/camellia.c
        ${libavutil_c}/cast5.c
        ${libavutil_c}/hwcontext.c
        ${libavutil_c}/film_grain_params.c
        ${libavutil_c}/display.c
        ${libavutil_c}/tx_float.c
        ${libavutil_c}/avstring.c
        ${libavutil_c}/ambient_viewing_environment.c
        ${libavutil_c}/log2_tab.c
        ${libavutil_c}/aes.c
        ${libavutil_c}/detection_bbox.c
        ${libavutil_c}/base64.c
        ${libavutil_c}/pixdesc.c
        ${libavutil_c}/encryption_info.c
        ${libavutil_c}/utils.c
        ${libavutil_c}/dict.c
        ${libavutil_c}/hwcontext_vaapi.c
        ${libavutil_c}/dovi_meta.c
        ${libavutil_c}/sha.c
        ${libavutil_c}/reverse.c
        ${libavutil_c}/samplefmt.c
        ${libavutil_c}/file_open.c
        ${libavutil_c}/float_dsp.c
        ${libavutil_c}/slicethread.c
        ${libavutil_c}/rc4.c
        ${libavutil_c}/threadmessage.c
        ${libavutil_c}/video_hint.c
        ${libavutil_c}/sha512.c
        ${libavutil_c}/blowfish.c
        ${libavutil_c}/hash.c
        ${libavutil_c}/timecode.c
        ${libavutil_c}/opt.c
        ${libavutil_c}/imgutils.c
        ${libavutil_c}/vulkan.c
        ${libavutil_c}/fifo.c
        ${libavutil_c}/integer.c
        ${libavutil_c}/x86/imgutils_init.c
        ${libavutil_c}/x86/cpu.c
        ${libavutil_c}/x86/fixed_dsp_init.c
        ${libavutil_c}/x86/lls_init.c
        ${libavutil_c}/x86/float_dsp_init.c
        ${libavutil_c}/x86/tx_float_init.c
        ${libavutil_c}/xga_font_data.c
        ${libavutil_c}/bprint.c
        ${libavutil_c}/hdr_dynamic_metadata.c
        ${libavutil_c}/lls.c
        ${libavutil_c}/log.c
        ${libavutil_c}/frame.c
        ${libavutil_c}/error.c
        ${libavutil_c}/rational.c
        ${libavutil_c}/mastering_display_metadata.c
        ${libavutil_c}/csp.c
        ${libavutil_c}/tree.c
        ${libavutil_c}/spherical.c
        ${libavutil_c}/tx_int32.c
        ${libavutil_c}/lzo.c
        ${libavutil_c}/hwcontext_vulkan.c
        ${libavutil_c}/hmac.c
        ${libavutil_c}/twofish.c
        ${libavutil_c}/crc.c
        ${libavutil_c}/channel_layout.c
        ${libavutil_c}/video_enc_params.c
        ${libavutil_c}/des.c
        ${libavutil_c}/aes_ctr.c
        ${libavutil_c}/hwcontext_stub.c
        ${libavutil_c}/eval.c
        ${libavutil_c}/mem.c
        ${libavutil_c}/uuid.c
        ${libavutil_c}/time.c
        ${libavutil_c}/tx.c
        ${libavutil_c}/avsscanf.c
)
set(avformat_c
        ${libavformat_c}/3dostr.c
        ${libavformat_c}/subviewer1dec.c
        ${libavformat_c}/hevcdec.c
        ${libavformat_c}/evcdec.c
        ${libavformat_c}/qtpalette.c
        ${libavformat_c}/nistspheredec.c
        ${libavformat_c}/qcp.c
        ${libavformat_c}/mxf.c
        ${libavformat_c}/gifdec.c
        ${libavformat_c}/aiffdec.c
        ${libavformat_c}/asfdec_o.c
        ${libavformat_c}/yuv4mpegdec.c
        ${libavformat_c}/derf.c
        ${libavformat_c}/mgsts.c
        ${libavformat_c}/asfcrypt.c
        ${libavformat_c}/mov_chan.c
        ${libavformat_c}/argo_brp.c
        ${libavformat_c}/rpl.c
        ${libavformat_c}/cdg.c
        ${libavformat_c}/g729dec.c
        ${libavformat_c}/4xm.c
        ${libavformat_c}/g726.c
        ${libavformat_c}/avio.c
        ${libavformat_c}/mux_utils.c
        ${libavformat_c}/jvdec.c
        ${libavformat_c}/sdxdec.c
        ${libavformat_c}/apm.c
        ${libavformat_c}/dss.c
        ${libavformat_c}/oggparsevorbis.c
        ${libavformat_c}/dsicin.c
        ${libavformat_c}/oma.c
        ${libavformat_c}/wavarc.c
        ${libavformat_c}/version.c
        ${libavformat_c}/av1dec.c
        ${libavformat_c}/msnwc_tcp.c
        ${libavformat_c}/xwma.c
        ${libavformat_c}/cinedec.c
        ${libavformat_c}/msf.c
        ${libavformat_c}/realtextdec.c
        ${libavformat_c}/swf.c
        ${libavformat_c}/idcin.c
        ${libavformat_c}/westwood_vqa.c
        ${libavformat_c}/boadec.c
        ${libavformat_c}/serdec.c
        ${libavformat_c}/mxg.c
        ${libavformat_c}/sauce.c
        ${libavformat_c}/mpc.c
        ${libavformat_c}/spdif.c
        ${libavformat_c}/microdvddec.c
        ${libavformat_c}/wady.c
        ${libavformat_c}/allformats.c
        ${libavformat_c}/lmlm4.c
        ${libavformat_c}/file.c
        ${libavformat_c}/ape.c
        ${libavformat_c}/aaxdec.c
        ${libavformat_c}/jpegxl_anim_dec.c
        ${libavformat_c}/ac4dec.c
        ${libavformat_c}/bethsoftvid.c
        ${libavformat_c}/act.c
        ${libavformat_c}/tee_common.c
        ${libavformat_c}/dxa.c
        ${libavformat_c}/data_uri.c
        ${libavformat_c}/svs.c
        ${libavformat_c}/vc1test.c
        ${libavformat_c}/tty.c
        ${libavformat_c}/pvfdec.c
        ${libavformat_c}/wvdec.c
        ${libavformat_c}/crypto.c
        ${libavformat_c}/aea.c
        ${libavformat_c}/sdp.c
        ${libavformat_c}/id3v1.c
        ${libavformat_c}/rso.c
        ${libavformat_c}/nuv.c
        ${libavformat_c}/luodatdec.c
        ${libavformat_c}/xmv.c
        ${libavformat_c}/m4vdec.c
        ${libavformat_c}/ac3dec.c
        ${libavformat_c}/flic.c
        ${libavformat_c}/genh.c
        ${libavformat_c}/id3v2.c
        ${libavformat_c}/apngdec.c
        ${libavformat_c}/adxdec.c
        ${libavformat_c}/g723_1.c
        ${libavformat_c}/wv.c
        ${libavformat_c}/avformat.c
        ${libavformat_c}/epafdec.c
        ${libavformat_c}/avidec.c
        ${libavformat_c}/prompeg.c
        ${libavformat_c}/h263dec.c
        ${libavformat_c}/dovi_isom.c
        ${libavformat_c}/cafdec.c
        ${libavformat_c}/oggparseskeleton.c
        ${libavformat_c}/rsodec.c
        ${libavformat_c}/mpl2dec.c
        ${libavformat_c}/hca.c
        ${libavformat_c}/subtitles.c
        ${libavformat_c}/ilbc.c
        ${libavformat_c}/vvcdec.c
        ${libavformat_c}/dauddec.c
        ${libavformat_c}/rawdec.c
        ${libavformat_c}/cavsvideodec.c
        ${libavformat_c}/dvbtxt.c
        ${libavformat_c}/srtdec.c
        ${libavformat_c}/mpeg.c
        ${libavformat_c}/sbcdec.c
        ${libavformat_c}/adp.c
        ${libavformat_c}/fwse.c
        ${libavformat_c}/icodec.c
        ${libavformat_c}/oggparseflac.c
        ${libavformat_c}/ads.c
        ${libavformat_c}/ffmetadec.c
        ${libavformat_c}/gdv.c
        ${libavformat_c}/binka.c
        ${libavformat_c}/brstm.c
        ${libavformat_c}/flacdec.c
        ${libavformat_c}/dhav.c
        ${libavformat_c}/soxdec.c
        ${libavformat_c}/mpegts.c
        ${libavformat_c}/wsddec.c
        ${libavformat_c}/takdec.c
        ${libavformat_c}/avs2dec.c
        ${libavformat_c}/sccdec.c
        ${libavformat_c}/isom.c
        ${libavformat_c}/avr.c
        ${libavformat_c}/smush.c
        ${libavformat_c}/fsb.c
        ${libavformat_c}/pcmdec.c
        ${libavformat_c}/sbgdec.c
        ${libavformat_c}/sdns.c
        ${libavformat_c}/mpsubdec.c
        ${libavformat_c}/utils.c
        ${libavformat_c}/oggparseogm.c
        ${libavformat_c}/nutdec.c
        ${libavformat_c}/rawvideodec.c
        ${libavformat_c}/kvag.c
        ${libavformat_c}/mux.c
        ${libavformat_c}/oggparsespeex.c
        ${libavformat_c}/aptxdec.c
        ${libavformat_c}/hnm.c
        ${libavformat_c}/redspark.c
        ${libavformat_c}/vividas.c
        ${libavformat_c}/oggdec.c
        ${libavformat_c}/ast.c
        ${libavformat_c}/mm.c
        ${libavformat_c}/hls_sample_encryption.c
        ${libavformat_c}/teeproto.c
        ${libavformat_c}/aadec.c
        ${libavformat_c}/psxstr.c
        ${libavformat_c}/musx.c
        ${libavformat_c}/frmdec.c
        ${libavformat_c}/img2.c
        ${libavformat_c}/argo_asf.c
        ${libavformat_c}/swfdec.c
        ${libavformat_c}/mlvdec.c
        ${libavformat_c}/rm.c
        ${libavformat_c}/c93.c
        ${libavformat_c}/rsd.c
        ${libavformat_c}/yop.c
        ${libavformat_c}/demux_utils.c
        ${libavformat_c}/segafilm.c
        ${libavformat_c}/ircamdec.c
        ${libavformat_c}/subviewerdec.c
        ${libavformat_c}/spdifdec.c
        ${libavformat_c}/mvdec.c
        ${libavformat_c}/mpegvideodec.c
        ${libavformat_c}/mpjpegdec.c
        ${libavformat_c}/pmpdec.c
        ${libavformat_c}/flvdec.c
        ${libavformat_c}/sdr2.c
        ${libavformat_c}/lafdec.c
        ${libavformat_c}/loasdec.c
        ${libavformat_c}/hlsproto.c
        ${libavformat_c}/mca.c
        ${libavformat_c}/vc1dec.c
        ${libavformat_c}/subfile.c
        ${libavformat_c}/mp3dec.c
        ${libavformat_c}/md5proto.c
        ${libavformat_c}/wtvdec.c
        ${libavformat_c}/siff.c
        ${libavformat_c}/nspdec.c
        ${libavformat_c}/ivfdec.c
        ${libavformat_c}/isom_tags.c
        ${libavformat_c}/img2_brender_pix.c
        ${libavformat_c}/iss.c
        ${libavformat_c}/mpc8.c
        ${libavformat_c}/cache.c
        ${libavformat_c}/lrc.c
        ${libavformat_c}/rka.c
        ${libavformat_c}/shortendec.c
        ${libavformat_c}/mccdec.c
        ${libavformat_c}/sierravmd.c
        ${libavformat_c}/mods.c
        ${libavformat_c}/sol.c
        ${libavformat_c}/usmdec.c
        ${libavformat_c}/dvbsub.c
        ${libavformat_c}/mvi.c
        ${libavformat_c}/s337m.c
        ${libavformat_c}/vqf.c
        ${libavformat_c}/gxf.c
        ${libavformat_c}/mtv.c
        ${libavformat_c}/hls.c
        ${libavformat_c}/anm.c
        ${libavformat_c}/protocols.c
        ${libavformat_c}/acm.c
        ${libavformat_c}/au.c
        ${libavformat_c}/mxfdec.c
        ${libavformat_c}/bmv.c
        ${libavformat_c}/svag.c
        ${libavformat_c}/aiff.c
        ${libavformat_c}/asfdec_f.c
        ${libavformat_c}/pdvdec.c
        ${libavformat_c}/img2_alias_pix.c
        ${libavformat_c}/afc.c
        ${libavformat_c}/voc.c
        ${libavformat_c}/iv8.c
        ${libavformat_c}/bit.c
        ${libavformat_c}/aviobuf.c
        ${libavformat_c}/asf.c
        ${libavformat_c}/dsfdec.c
        ${libavformat_c}/dtsdec.c
        ${libavformat_c}/lrcdec.c
        ${libavformat_c}/concat.c
        ${libavformat_c}/mlpdec.c
        ${libavformat_c}/smjpegdec.c
        ${libavformat_c}/ingenientdec.c
        ${libavformat_c}/sdsdec.c
        ${libavformat_c}/gsmdec.c
        ${libavformat_c}/vorbiscomment.c
        ${libavformat_c}/rl2.c
        ${libavformat_c}/w64.c
        ${libavformat_c}/bink.c
        ${libavformat_c}/oggparseopus.c
        ${libavformat_c}/nsvdec.c
        ${libavformat_c}/tedcaptionsdec.c
        ${libavformat_c}/ipudec.c
        ${libavformat_c}/cdxl.c
        ${libavformat_c}/h264dec.c
        ${libavformat_c}/samidec.c
        ${libavformat_c}/scd.c
        ${libavformat_c}/supdec.c
        ${libavformat_c}/oggparsecelt.c
        ${libavformat_c}/avs3dec.c
        ${libavformat_c}/lvfdec.c
        ${libavformat_c}/url.c
        ${libavformat_c}/xa.c
        ${libavformat_c}/mov_esds.c
        ${libavformat_c}/fitsdec.c
        ${libavformat_c}/metadata.c
        ${libavformat_c}/hcom.c
        ${libavformat_c}/acedec.c
        ${libavformat_c}/xmd.c
        ${libavformat_c}/wtv_common.c
        ${libavformat_c}/vpk.c
        ${libavformat_c}/aacdec.c
        ${libavformat_c}/smacker.c
        ${libavformat_c}/ty.c
        ${libavformat_c}/async.c
        ${libavformat_c}/imx.c
        ${libavformat_c}/riffdec.c
        ${libavformat_c}/astdec.c
        ${libavformat_c}/dtshddec.c
        ${libavformat_c}/westwood_aud.c
        ${libavformat_c}/assdec.c
        ${libavformat_c}/tmv.c
        ${libavformat_c}/concatdec.c
        ${libavformat_c}/txd.c
        ${libavformat_c}/pp_bnk.c
        ${libavformat_c}/dfpwmdec.c
        ${libavformat_c}/wavdec.c
        ${libavformat_c}/avs.c
        ${libavformat_c}/matroskadec.c
        ${libavformat_c}/sga.c
        ${libavformat_c}/avlanguage.c
        ${libavformat_c}/tta.c
        ${libavformat_c}/ifv.c
        ${libavformat_c}/iff.c
        ${libavformat_c}/bfi.c
        ${libavformat_c}/argo_cvg.c
        ${libavformat_c}/smjpeg.c
        ${libavformat_c}/options.c
        ${libavformat_c}/g722.c
        ${libavformat_c}/replaygain.c
        ${libavformat_c}/filmstripdec.c
        ${libavformat_c}/pcm.c
        ${libavformat_c}/idroqdec.c
        ${libavformat_c}/pva.c
        ${libavformat_c}/voc_packet.c
        ${libavformat_c}/ncdec.c
        ${libavformat_c}/bintext.c
        ${libavformat_c}/mov.c
        ${libavformat_c}/caf.c
        ${libavformat_c}/r3d.c
        ${libavformat_c}/paf.c
        ${libavformat_c}/rmsipr.c
        ${libavformat_c}/dcstr.c
        ${libavformat_c}/bonk.c
        ${libavformat_c}/electronicarts.c
        ${libavformat_c}/aixdec.c
        ${libavformat_c}/tiertexseq.c
        ${libavformat_c}/lxfdec.c
        ${libavformat_c}/mmf.c
        ${libavformat_c}/webvttdec.c
        ${libavformat_c}/vivo.c
        ${libavformat_c}/vag.c
        ${libavformat_c}/mspdec.c
        ${libavformat_c}/mtaf.c
        ${libavformat_c}/apc.c
        ${libavformat_c}/eacdata.c
        ${libavformat_c}/dnxhddec.c
        ${libavformat_c}/demux.c
        ${libavformat_c}/asf_tags.c
        ${libavformat_c}/pjsdec.c
        ${libavformat_c}/aqtitledec.c
        ${libavformat_c}/dfa.c
        ${libavformat_c}/apetag.c
        ${libavformat_c}/seek.c
        ${libavformat_c}/wvedec.c
        ${libavformat_c}/amr.c
        ${libavformat_c}/stldec.c
        ${libavformat_c}/oggparsedirac.c
        ${libavformat_c}/dv.c
        ${libavformat_c}/nut.c
        ${libavformat_c}/wc3movie.c
        ${libavformat_c}/jacosubdec.c
        ${libavformat_c}/dump.c
        ${libavformat_c}/apac.c
        ${libavformat_c}/riff.c
        ${libavformat_c}/flac_picture.c
        ${libavformat_c}/xvag.c
        ${libavformat_c}/img2dec.c
        ${libavformat_c}/thp.c
        ${libavformat_c}/rmdec.c
        ${libavformat_c}/os_support.c
        ${libavformat_c}/matroska.c
        ${libavformat_c}/codec2.c
        ${libavformat_c}/oggparsetheora.c
        ${libavformat_c}/mj2kdec.c
        ${libavformat_c}/moflex.c
        ${libavformat_c}/oggparsevp8.c
        ${libavformat_c}/vplayerdec.c
        ${libavformat_c}/diracdec.c
        ${libavformat_c}/alp.c
        ${libavformat_c}/format.c
        ${libavformat_c}/omadec.c
        ${libavformat_c}/h261dec.c
        ${libavformat_c}/ircam.c
        ${libavformat_c}/osq.c
        ${libavformat_c}/vocdec.c
        ${libavformat_c}/ipmovie.c
)
set(avcodec_c
        ${libavcodec_c}/eac3_data.c
        ${libavcodec_c}/mpegaudiodsp_fixed.c
        ${libavcodec_c}/cyuv.c
        ${libavcodec_c}/dirac.c
        ${libavcodec_c}/tiff.c
        ${libavcodec_c}/ccaption_dec.c
        ${libavcodec_c}/hevcdec.c
        ${libavcodec_c}/adpcm.c
        ${libavcodec_c}/acelp_pitch_delay.c
        ${libavcodec_c}/ilbcdec.c
        ${libavcodec_c}/cavs_parser.c
        ${libavcodec_c}/parsers.c
        ${libavcodec_c}/mpeg4_unpack_bframes_bsf.c
        ${libavcodec_c}/dvd_nav_parser.c
        ${libavcodec_c}/ulti.c
        ${libavcodec_c}/kmvc.c
        ${libavcodec_c}/gifdec.c
        ${libavcodec_c}/hdr_parser.c
        ${libavcodec_c}/wavpack.c
        ${libavcodec_c}/vbndec.c
        ${libavcodec_c}/vp9mvs.c
        ${libavcodec_c}/h264_redundant_pps_bsf.c
        ${libavcodec_c}/vc1data.c
        ${libavcodec_c}/opus_parser.c
        ${libavcodec_c}/roqvideodec.c
        ${libavcodec_c}/exif.c
        ${libavcodec_c}/qdmc.c
        ${libavcodec_c}/atsc_a53.c
        ${libavcodec_c}/dct32_fixed.c
        ${libavcodec_c}/atrac1.c
        ${libavcodec_c}/eaidct.c
        ${libavcodec_c}/mpegaudiodsp_data.c
        ${libavcodec_c}/magicyuv.c
        ${libavcodec_c}/interplayacm.c
        ${libavcodec_c}/vp9_metadata_bsf.c
        ${libavcodec_c}/videodsp.c
        ${libavcodec_c}/vp56dsp.c
        ${libavcodec_c}/h264_cabac.c
        ${libavcodec_c}/jpegquanttables.c
        ${libavcodec_c}/mss3.c
        ${libavcodec_c}/g729dec.c
        ${libavcodec_c}/4xm.c
        ${libavcodec_c}/bmp_parser.c
        ${libavcodec_c}/g726.c
        ${libavcodec_c}/sbrdsp_fixed.c
        ${libavcodec_c}/avs2.c
        ${libavcodec_c}/webp_parser.c
        ${libavcodec_c}/g723_1_parser.c
        ${libavcodec_c}/dolby_e_parser.c
        ${libavcodec_c}/r210dec.c
        ${libavcodec_c}/h264_levels.c
        ${libavcodec_c}/proresdec2.c
        ${libavcodec_c}/jvdec.c
        ${libavcodec_c}/latm_parser.c
        ${libavcodec_c}/cabac.c
        ${libavcodec_c}/s302m.c
        ${libavcodec_c}/flacdsp.c
        ${libavcodec_c}/mpegaudiodec_float.c
        ${libavcodec_c}/apedec.c
        ${libavcodec_c}/cbs_vp9.c
        ${libavcodec_c}/celp_math.c
        ${libavcodec_c}/vp9_raw_reorder_bsf.c
        ${libavcodec_c}/bswapdsp.c
        ${libavcodec_c}/pixlet.c
        ${libavcodec_c}/remove_extradata_bsf.c
        ${libavcodec_c}/movsub_bsf.c
        ${libavcodec_c}/dovi_rpu.c
        ${libavcodec_c}/pcx.c
        ${libavcodec_c}/scpr.c
        ${libavcodec_c}/xsubdec.c
        ${libavcodec_c}/pnmdec.c
        ${libavcodec_c}/hapdec.c
        ${libavcodec_c}/mvcdec.c
        ${libavcodec_c}/cllc.c
        ${libavcodec_c}/cpia.c
        ${libavcodec_c}/imc.c
        ${libavcodec_c}/wavarc.c
        ${libavcodec_c}/version.c
        ${libavcodec_c}/av1dec.c
        ${libavcodec_c}/mjpegbdec.c
        ${libavcodec_c}/huffyuv.c
        ${libavcodec_c}/evc_frame_merge_bsf.c
        ${libavcodec_c}/imx_dump_header_bsf.c
        ${libavcodec_c}/notchlc.c
        ${libavcodec_c}/half2float.c
        ${libavcodec_c}/mlp_parser.c
        ${libavcodec_c}/dump_extradata_bsf.c
        ${libavcodec_c}/aacdec_fixed.c
        ${libavcodec_c}/utvideodec.c
        ${libavcodec_c}/atrac9dec.c
        ${libavcodec_c}/adx.c
        ${libavcodec_c}/aac_parser.c
        ${libavcodec_c}/realtextdec.c
        ${libavcodec_c}/h265_metadata_bsf.c
        ${libavcodec_c}/gsm_parser.c
        ${libavcodec_c}/vp9lpf.c
        ${libavcodec_c}/aac_ac3_parser.c
        ${libavcodec_c}/mpegvideo_parser.c
        ${libavcodec_c}/bmvvideo.c
        ${libavcodec_c}/arbc.c
        ${libavcodec_c}/wmalosslessdec.c
        ${libavcodec_c}/ac3tab.c
        ${libavcodec_c}/mpc.c
        ${libavcodec_c}/dca.c
        ${libavcodec_c}/alac.c
        ${libavcodec_c}/wma_freqs.c
        ${libavcodec_c}/v4l2_buffers.c
        ${libavcodec_c}/microdvddec.c
        ${libavcodec_c}/pcm-bluray.c
        ${libavcodec_c}/sbc_parser.c
        ${libavcodec_c}/sinewin.c
        ${libavcodec_c}/agm.c
        ${libavcodec_c}/avfft.c
        ${libavcodec_c}/cbs.c
        ${libavcodec_c}/av1_metadata_bsf.c
        ${libavcodec_c}/eatqi.c
        ${libavcodec_c}/vpx_rac.c
        ${libavcodec_c}/qoidec.c
        ${libavcodec_c}/mobiclip.c
        ${libavcodec_c}/mjpeg2jpeg_bsf.c
        ${libavcodec_c}/hevc_cabac.c
        ${libavcodec_c}/xma_parser.c
        ${libavcodec_c}/dxtory.c
        ${libavcodec_c}/v4l2_fmt.c
        ${libavcodec_c}/msrle.c
        ${libavcodec_c}/ipu_parser.c
        ${libavcodec_c}/lossless_audiodsp.c
        ${libavcodec_c}/mpeg4audio_sample_rates.c
        ${libavcodec_c}/lsp.c
        ${libavcodec_c}/vorbisdsp.c
        ${libavcodec_c}/roqvideo.c
        ${libavcodec_c}/bitstream.c
        ${libavcodec_c}/allcodecs.c
        ${libavcodec_c}/dsicinvideo.c
        ${libavcodec_c}/xbmdec.c
        ${libavcodec_c}/hevc_data.c
        ${libavcodec_c}/avpacket.c
        ${libavcodec_c}/vp6.c
        ${libavcodec_c}/cbs_h2645.c
        ${libavcodec_c}/hpeldsp.c
        ${libavcodec_c}/xbm_parser.c
        ${libavcodec_c}/bmvaudio.c
        ${libavcodec_c}/dvaudiodec.c
        ${libavcodec_c}/h2645_parse.c
        ${libavcodec_c}/eamad.c
        ${libavcodec_c}/dolby_e_parse.c
        ${libavcodec_c}/bmp.c
        ${libavcodec_c}/dds.c
        ${libavcodec_c}/lzf.c
        ${libavcodec_c}/nuv.c
        ${libavcodec_c}/svq1dec.c
        ${libavcodec_c}/dvaudio_parser.c
        ${libavcodec_c}/avs3_parser.c
        ${libavcodec_c}/movtextdec.c
        ${libavcodec_c}/mjpegdec.c
        ${libavcodec_c}/dct32_float.c
        ${libavcodec_c}/sipr_parser.c
        ${libavcodec_c}/h264pred.c
        ${libavcodec_c}/opus_parse.c
        ${libavcodec_c}/wma.c
        ${libavcodec_c}/msvideo1.c
        ${libavcodec_c}/aacsbr.c
        ${libavcodec_c}/aandcttab.c
        ${libavcodec_c}/dvdata.c
        ${libavcodec_c}/acelp_vectors.c
        ${libavcodec_c}/hevc_filter.c
        ${libavcodec_c}/vp3.c
        ${libavcodec_c}/wavpackdata.c
        ${libavcodec_c}/null.c
        ${libavcodec_c}/hq_hqadata.c
        ${libavcodec_c}/mpeg12.c
        ${libavcodec_c}/mpeg12framerate.c
        ${libavcodec_c}/hevcdsp.c
        ${libavcodec_c}/brenderpix.c
        ${libavcodec_c}/adxdec.c
        ${libavcodec_c}/dvdsubdec.c
        ${libavcodec_c}/g723_1.c
        ${libavcodec_c}/sbrdsp.c
        ${libavcodec_c}/celp_filters.c
        ${libavcodec_c}/mp3_header_decompress_bsf.c
        ${libavcodec_c}/cbrt_data.c
        ${libavcodec_c}/h264_metadata_bsf.c
        ${libavcodec_c}/avcodec.c
        ${libavcodec_c}/vp9_superframe_split_bsf.c
        ${libavcodec_c}/hqxdsp.c
        ${libavcodec_c}/msp2dec.c
        ${libavcodec_c}/ac3_channel_layout_tab.c
        ${libavcodec_c}/mdec.c
        ${libavcodec_c}/lossless_videodsp.c
        ${libavcodec_c}/mjpegdec_common.c
        ${libavcodec_c}/frwu.c
        ${libavcodec_c}/cavsdec.c
        ${libavcodec_c}/truemotion1.c
        ${libavcodec_c}/texturedsp.c
        ${libavcodec_c}/mpl2dec.c
        ${libavcodec_c}/cri_parser.c
        ${libavcodec_c}/h264_sei.c
        ${libavcodec_c}/pthread_frame.c
        ${libavcodec_c}/h264qpel.c
        ${libavcodec_c}/psd.c
        ${libavcodec_c}/xwddec.c
        ${libavcodec_c}/jpeg2000dec.c
        ${libavcodec_c}/vmixdec.c
        ${libavcodec_c}/sp5xdec.c
        ${libavcodec_c}/misc4_parser.c
        ${libavcodec_c}/pnm.c
        ${libavcodec_c}/codec_par.c
        ${libavcodec_c}/h263data.c
        ${libavcodec_c}/rawdec.c
        ${libavcodec_c}/msgsmdec.c
        ${libavcodec_c}/vc1.c
        ${libavcodec_c}/vp9dsp_12bpp.c
        ${libavcodec_c}/dcadsp.c
        ${libavcodec_c}/aic.c
        ${libavcodec_c}/asv.c
        ${libavcodec_c}/mjpega_dump_header_bsf.c
        ${libavcodec_c}/cook_parser.c
        ${libavcodec_c}/srtdec.c
        ${libavcodec_c}/sbcdec.c
        ${libavcodec_c}/mpegutils.c
        ${libavcodec_c}/aacps_common.c
        ${libavcodec_c}/h264dsp.c
        ${libavcodec_c}/mxpegdec.c
        ${libavcodec_c}/mace.c
        ${libavcodec_c}/bitpacked_dec.c
        ${libavcodec_c}/g722dsp.c
        ${libavcodec_c}/kbdwin.c
        ${libavcodec_c}/dvdsub_parser.c
        ${libavcodec_c}/argo.c
        ${libavcodec_c}/gdv.c
        ${libavcodec_c}/cbs_av1.c
        ${libavcodec_c}/dca_lbr.c
        ${libavcodec_c}/mpegaudiodecheader.c
        ${libavcodec_c}/hevcpred.c
        ${libavcodec_c}/imm4.c
        ${libavcodec_c}/h2645_sei.c
        ${libavcodec_c}/flacdec.c
        ${libavcodec_c}/jpegtables.c
        ${libavcodec_c}/truemotion2.c
        ${libavcodec_c}/h266_metadata_bsf.c
        ${libavcodec_c}/sonic.c
        ${libavcodec_c}/webp.c
        ${libavcodec_c}/h264_slice.c
        ${libavcodec_c}/lcldec.c
        ${libavcodec_c}/vp9dsp_8bpp.c
        ${libavcodec_c}/takdec.c
        ${libavcodec_c}/jpegls.c
        ${libavcodec_c}/cinepak.c
        ${libavcodec_c}/vp9block.c
        ${libavcodec_c}/vqcdec.c
        ${libavcodec_c}/cfhd.c
        ${libavcodec_c}/dca_exss.c
        ${libavcodec_c}/indeo3.c
        ${libavcodec_c}/hevc_parse.c
        ${libavcodec_c}/h264chroma.c
        ${libavcodec_c}/truespeech.c
        ${libavcodec_c}/mlp.c
        ${libavcodec_c}/hevc_sei.c
        ${libavcodec_c}/sbc.c
        ${libavcodec_c}/midivid.c
        ${libavcodec_c}/ra288.c
        ${libavcodec_c}/vp56data.c
        ${libavcodec_c}/null_bsf.c
        ${libavcodec_c}/speedhq.c
        ${libavcodec_c}/xiph.c
        ${libavcodec_c}/dcadata.c
        ${libavcodec_c}/jpegxl_parse.c
        ${libavcodec_c}/atrac3plus.c
        ${libavcodec_c}/vp9.c
        ${libavcodec_c}/dnxhddata.c
        ${libavcodec_c}/utils.c
        ${libavcodec_c}/y41pdec.c
        ${libavcodec_c}/mpeg4audio.c
        ${libavcodec_c}/v308dec.c
        ${libavcodec_c}/qoi_parser.c
        ${libavcodec_c}/dpx.c
        ${libavcodec_c}/gemdec.c
        ${libavcodec_c}/bethsoftvideo.c
        ${libavcodec_c}/pnm_parser.c
        ${libavcodec_c}/gif_parser.c
        ${libavcodec_c}/dxv.c
        ${libavcodec_c}/aptxdec.c
        ${libavcodec_c}/bgmc.c
        ${libavcodec_c}/pictordec.c
        ${libavcodec_c}/ttadsp.c
        ${libavcodec_c}/cfhddsp.c
        ${libavcodec_c}/h264_direct.c
        ${libavcodec_c}/flicvideo.c
        ${libavcodec_c}/chomp_bsf.c
        ${libavcodec_c}/ptx.c
        ${libavcodec_c}/xpmdec.c
        ${libavcodec_c}/mlz.c
        ${libavcodec_c}/aactab.c
        ${libavcodec_c}/hq_hqadsp.c
        ${libavcodec_c}/shorten.c
        ${libavcodec_c}/pgs_frame_merge_bsf.c
        ${libavcodec_c}/cbs_mpeg2.c
        ${libavcodec_c}/nellymoserdec.c
        ${libavcodec_c}/dca_parser.c
        ${libavcodec_c}/mjpeg_parser.c
        ${libavcodec_c}/8svx.c
        ${libavcodec_c}/ansi.c
        ${libavcodec_c}/cdgraphics.c
        ${libavcodec_c}/photocd.c
        ${libavcodec_c}/mpegaudiodsp_float.c
        ${libavcodec_c}/eatgq.c
        ${libavcodec_c}/h264_loopfilter.c
        ${libavcodec_c}/vcr1.c
        ${libavcodec_c}/cfhddata.c
        ${libavcodec_c}/decode.c
        ${libavcodec_c}/h264idct.c
        ${libavcodec_c}/adx_parser.c
        ${libavcodec_c}/vp8.c
        ${libavcodec_c}/refstruct.c
        ${libavcodec_c}/tiff_common.c
        ${libavcodec_c}/ws-snd1.c
        ${libavcodec_c}/pgxdec.c
        ${libavcodec_c}/mediacodec.c
        ${libavcodec_c}/huffman.c
        ${libavcodec_c}/aasc.c
        ${libavcodec_c}/prosumer.c
        ${libavcodec_c}/idctdsp.c
        ${libavcodec_c}/c93.c
        ${libavcodec_c}/xfacedec.c
        ${libavcodec_c}/misc4.c
        ${libavcodec_c}/yop.c
        ${libavcodec_c}/eac3_core_bsf.c
        ${libavcodec_c}/huffyuvdsp.c
        ${libavcodec_c}/aacsbr_fixed.c
        ${libavcodec_c}/avrndec.c
        ${libavcodec_c}/vp56.c
        ${libavcodec_c}/evc_parse.c
        ${libavcodec_c}/dca_xll.c
        ${libavcodec_c}/ra144.c
        ${libavcodec_c}/vp9prob.c
        ${libavcodec_c}/atrac3plusdsp.c
        ${libavcodec_c}/v408dec.c
        ${libavcodec_c}/msrledec.c
        ${libavcodec_c}/subviewerdec.c
        ${libavcodec_c}/adts_parser.c
        ${libavcodec_c}/mathtables.c
        ${libavcodec_c}/cga_data.c
        ${libavcodec_c}/dca_sample_rate_tab.c
        ${libavcodec_c}/jni.c
        ${libavcodec_c}/rangecoder.c
        ${libavcodec_c}/xxan.c
        ${libavcodec_c}/vqavideo.c
        ${libavcodec_c}/dirac_parser.c
        ${libavcodec_c}/truemotion2rt.c
        ${libavcodec_c}/cscd.c
        ${libavcodec_c}/dvdec.c
        ${libavcodec_c}/vc1dsp.c
        ${libavcodec_c}/ffwavesynth.c
        ${libavcodec_c}/pafvideo.c
        ${libavcodec_c}/tak_parser.c
        ${libavcodec_c}/atrac.c
        ${libavcodec_c}/h264_cavlc.c
        ${libavcodec_c}/hap.c
        ${libavcodec_c}/012v.c
        ${libavcodec_c}/vble.c
        ${libavcodec_c}/eacmv.c
        ${libavcodec_c}/wmv2data.c
        ${libavcodec_c}/hevc_parser.c
        ${libavcodec_c}/cbs_sei.c
        ${libavcodec_c}/tscc2.c
        ${libavcodec_c}/ac3dec_float.c
        ${libavcodec_c}/ac3dsp.c
        ${libavcodec_c}/jpeglsdec.c
        ${libavcodec_c}/v4l2_m2m.c
        ${libavcodec_c}/vaapi_decode.c
        ${libavcodec_c}/sgidec.c
        ${libavcodec_c}/dv_error_marker_bsf.c
        ${libavcodec_c}/jpeg2000.c
        ${libavcodec_c}/binkdsp.c
        ${libavcodec_c}/ralf.c
        ${libavcodec_c}/faxcompr.c
        ${libavcodec_c}/indeo4.c
        ${libavcodec_c}/h264_parse.c
        ${libavcodec_c}/vp9dsp_10bpp.c
        ${libavcodec_c}/qpeldsp.c
        ${libavcodec_c}/mpc8.c
        ${libavcodec_c}/vp3dsp.c
        ${libavcodec_c}/rka.c
        ${libavcodec_c}/hcadec.c
        ${libavcodec_c}/jpegxl_parser.c
        ${libavcodec_c}/hqxvlc.c
        ${libavcodec_c}/h264_mb.c
        ${libavcodec_c}/mpegaudiotabs.c
        ${libavcodec_c}/dts2pts_bsf.c
        ${libavcodec_c}/takdsp.c
        ${libavcodec_c}/jrevdct.c
        ${libavcodec_c}/idcinvideo.c
        ${libavcodec_c}/avuidec.c
        ${libavcodec_c}/pcm-dvd.c
        ${libavcodec_c}/cdtoons.c
        ${libavcodec_c}/lagarithrac.c
        ${libavcodec_c}/dvbsub_parser.c
        ${libavcodec_c}/h263_parser.c
        ${libavcodec_c}/av1_frame_split_bsf.c
        ${libavcodec_c}/targa.c
        ${libavcodec_c}/synth_filter.c
        ${libavcodec_c}/tak.c
        ${libavcodec_c}/vulkan.c
        ${libavcodec_c}/anm.c
        ${libavcodec_c}/utvideodsp.c
        ${libavcodec_c}/mpegaudiodec_fixed.c
        ${libavcodec_c}/golomb.c
        ${libavcodec_c}/alsdec.c
        ${libavcodec_c}/aliaspixdec.c
        ${libavcodec_c}/mss12.c
        ${libavcodec_c}/cngdec.c
        ${libavcodec_c}/d3d11va.c
        ${libavcodec_c}/proresdsp.c
        ${libavcodec_c}/dcadec.c
        ${libavcodec_c}/dvdsub.c
        ${libavcodec_c}/vc1_parser.c
        ${libavcodec_c}/h264_ps.c
        ${libavcodec_c}/sunrast.c
        ${libavcodec_c}/canopus.c
        ${libavcodec_c}/wma_common.c
        ${libavcodec_c}/media100_to_mjpegb_bsf.c
        ${libavcodec_c}/aacps_float.c
        ${libavcodec_c}/cavs.c
        ${libavcodec_c}/dsddec.c
        ${libavcodec_c}/hapqa_extract_bsf.c
        ${libavcodec_c}/hdrdec.c
        ${libavcodec_c}/vp5.c
        ${libavcodec_c}/av1_parser.c
        ${libavcodec_c}/dcadct.c
        ${libavcodec_c}/smc.c
        ${libavcodec_c}/setts_bsf.c
        ${libavcodec_c}/ivi.c
        ${libavcodec_c}/dca_core_bsf.c
        ${libavcodec_c}/sgirledec.c
        ${libavcodec_c}/qdm2.c
        ${libavcodec_c}/truehd_core_bsf.c
        ${libavcodec_c}/aura.c
        ${libavcodec_c}/vmdvideo.c
        ${libavcodec_c}/fraps.c
        ${libavcodec_c}/lzw.c
        ${libavcodec_c}/acelp_filters.c
        ${libavcodec_c}/codec_desc.c
        ${libavcodec_c}/v210x.c
        ${libavcodec_c}/sheervideo.c
        ${libavcodec_c}/ac3_parser.c
        ${libavcodec_c}/pthread.c
        ${libavcodec_c}/vp9data.c
        ${libavcodec_c}/avs2_parser.c
        ${libavcodec_c}/sbcdec_data.c
        ${libavcodec_c}/x86/h264_intrapred_init.c
        ${libavcodec_c}/x86/constants.c
        ${libavcodec_c}/x86/vp9dsp_init_16bpp.c
        ${libavcodec_c}/x86/videodsp_init.c
        ${libavcodec_c}/x86/vp9dsp_init.c
        ${libavcodec_c}/x86/h264_qpel.c
        ${libavcodec_c}/x86/h264dsp_init.c
        ${libavcodec_c}/x86/vp9dsp_init_12bpp.c
        ${libavcodec_c}/x86/h264chroma_init.c
        ${libavcodec_c}/x86/vp9dsp_init_10bpp.c
        ${libavcodec_c}/mpc7.c
        ${libavcodec_c}/dss_sp.c
        ${libavcodec_c}/mlpdec.c
        ${libavcodec_c}/h2645_vui.c
        ${libavcodec_c}/mss34dsp.c
        ${libavcodec_c}/vp8_parser.c
        ${libavcodec_c}/clearvideo.c
        ${libavcodec_c}/gsmdec.c
        ${libavcodec_c}/wrapped_avframe.c
        ${libavcodec_c}/rl2.c
        ${libavcodec_c}/startcode.c
        ${libavcodec_c}/blockdsp.c
        ${libavcodec_c}/svq1.c
        ${libavcodec_c}/bink.c
        ${libavcodec_c}/dsd.c
        ${libavcodec_c}/get_buffer.c
        ${libavcodec_c}/eatgv.c
        ${libavcodec_c}/proresdata.c
        ${libavcodec_c}/vorbis.c
        ${libavcodec_c}/dcahuff.c
        ${libavcodec_c}/audiodsp.c
        ${libavcodec_c}/cri.c
        ${libavcodec_c}/ac3dec_fixed.c
        ${libavcodec_c}/ffv1dec.c
        ${libavcodec_c}/atrac3.c
        ${libavcodec_c}/cdxl.c
        ${libavcodec_c}/h264dec.c
        ${libavcodec_c}/nellymoser.c
        ${libavcodec_c}/samidec.c
        ${libavcodec_c}/prores_metadata_bsf.c
        ${libavcodec_c}/to_upper4.c
        ${libavcodec_c}/tiertexseqv.c
        ${libavcodec_c}/dnxhd_parser.c
        ${libavcodec_c}/mmvideo.c
        ${libavcodec_c}/loco.c
        ${libavcodec_c}/xface.c
        ${libavcodec_c}/mpegaudiodec_common.c
        ${libavcodec_c}/mss1.c
        ${libavcodec_c}/fitsdec.c
        ${libavcodec_c}/ffv1.c
        ${libavcodec_c}/h264_picture.c
        ${libavcodec_c}/hcom.c
        ${libavcodec_c}/rtv1.c
        ${libavcodec_c}/mv30.c
        ${libavcodec_c}/imm5.c
        ${libavcodec_c}/aacpsdsp_fixed.c
        ${libavcodec_c}/imgconvert.c
        ${libavcodec_c}/aacdec.c
        ${libavcodec_c}/smacker.c
        ${libavcodec_c}/wbmpdec.c
        ${libavcodec_c}/ac3dec_data.c
        ${libavcodec_c}/imx.c
        ${libavcodec_c}/parser.c
        ${libavcodec_c}/av1_frame_merge_bsf.c
        ${libavcodec_c}/motionpixels.c
        ${libavcodec_c}/vb.c
        ${libavcodec_c}/ivi_dsp.c
        ${libavcodec_c}/h265_profile_level.c
        ${libavcodec_c}/binkaudio.c
        ${libavcodec_c}/8bps.c
        ${libavcodec_c}/av1_parse.c
        ${libavcodec_c}/speedhqdec.c
        ${libavcodec_c}/hevc_refs.c
        ${libavcodec_c}/trace_headers_bsf.c
        ${libavcodec_c}/mqc.c
        ${libavcodec_c}/assdec.c
        ${libavcodec_c}/tmv.c
        ${libavcodec_c}/opus_metadata_bsf.c
        ${libavcodec_c}/adts_header.c
        ${libavcodec_c}/dsicinaudio.c
        ${libavcodec_c}/h264_refs.c
        ${libavcodec_c}/vima.c
        ${libavcodec_c}/rv34_parser.c
        ${libavcodec_c}/jpeg2000dsp.c
        ${libavcodec_c}/cbs_bsf.c
        ${libavcodec_c}/pgssubdec.c
        ${libavcodec_c}/mpegaudio.c
        ${libavcodec_c}/noise_bsf.c
        ${libavcodec_c}/evc_parser.c
        ${libavcodec_c}/dca_core.c
        ${libavcodec_c}/flac.c
        ${libavcodec_c}/txd.c
        ${libavcodec_c}/kgv1dec.c
        ${libavcodec_c}/vorbis_data.c
        ${libavcodec_c}/wmaprodec.c
        ${libavcodec_c}/vp8data.c
        ${libavcodec_c}/dfpwmdec.c
        ${libavcodec_c}/avs.c
        ${libavcodec_c}/sga.c
        ${libavcodec_c}/avdct.c
        ${libavcodec_c}/tta.c
        ${libavcodec_c}/v210dec.c
        ${libavcodec_c}/escape130.c
        ${libavcodec_c}/iff.c
        ${libavcodec_c}/atrac3plusdec.c
        ${libavcodec_c}/dolby_e.c
        ${libavcodec_c}/aacpsdsp_float.c
        ${libavcodec_c}/alac_data.c
        ${libavcodec_c}/bfi.c
        ${libavcodec_c}/qsv_api.c
        ${libavcodec_c}/escape124.c
        ${libavcodec_c}/dpcm.c
        ${libavcodec_c}/options.c
        ${libavcodec_c}/aptx.c
        ${libavcodec_c}/g722.c
        ${libavcodec_c}/ass.c
        ${libavcodec_c}/h274.c
        ${libavcodec_c}/aacps_fixed.c
        ${libavcodec_c}/g722dec.c
        ${libavcodec_c}/pcm.c
        ${libavcodec_c}/vp6dsp.c
        ${libavcodec_c}/dynamic_hdr_vivid.c
        ${libavcodec_c}/hevc_ps.c
        ${libavcodec_c}/pthread_slice.c
        ${libavcodec_c}/vp9dsp.c
        ${libavcodec_c}/aac_adtstoasc_bsf.c
        ${libavcodec_c}/xan.c
        ${libavcodec_c}/bintext.c
        ${libavcodec_c}/wnv1.c
        ${libavcodec_c}/mpegaudiodsp.c
        ${libavcodec_c}/speexdec.c
        ${libavcodec_c}/jpeg2000htdec.c
        ${libavcodec_c}/bonk.c
        ${libavcodec_c}/cljrdec.c
        ${libavcodec_c}/vorbisdec.c
        ${libavcodec_c}/pcm_rechunk_bsf.c
        ${libavcodec_c}/bsf.c
        ${libavcodec_c}/mpeg12data.c
        ${libavcodec_c}/rpza.c
        ${libavcodec_c}/webvttdec.c
        ${libavcodec_c}/encode.c
        ${libavcodec_c}/dpx_parser.c
        ${libavcodec_c}/v410dec.c
        ${libavcodec_c}/mpegaudio_parser.c
        ${libavcodec_c}/mpeg2_metadata_bsf.c
        ${libavcodec_c}/g729postfilter.c
        ${libavcodec_c}/yuv4dec.c
        ${libavcodec_c}/gsmdec_data.c
        ${libavcodec_c}/snappy.c
        ${libavcodec_c}/v4l2_context.c
        ${libavcodec_c}/lagarith.c
        ${libavcodec_c}/dnxhddec.c
        ${libavcodec_c}/vlc.c
        ${libavcodec_c}/dv_profile.c
        ${libavcodec_c}/jpeg2000dwt.c
        ${libavcodec_c}/filter_units_bsf.c
        ${libavcodec_c}/evc_ps.c
        ${libavcodec_c}/huffyuvdec.c
        ${libavcodec_c}/h2645data.c
        ${libavcodec_c}/profiles.c
        ${libavcodec_c}/xwd_parser.c
        ${libavcodec_c}/indeo5.c
        ${libavcodec_c}/dfa.c
        ${libavcodec_c}/fits.c
        ${libavcodec_c}/vmnc.c
        ${libavcodec_c}/fmtconvert.c
        ${libavcodec_c}/dstdec.c
        ${libavcodec_c}/alacdsp.c
        ${libavcodec_c}/pafaudio.c
        ${libavcodec_c}/mss4.c
        ${libavcodec_c}/interplayvideo.c
        ${libavcodec_c}/fastaudio.c
        ${libavcodec_c}/wmadec.c
        ${libavcodec_c}/textdec.c
        ${libavcodec_c}/qpeg.c
        ${libavcodec_c}/cavsdsp.c
        ${libavcodec_c}/vorbis_parser.c
        ${libavcodec_c}/hnm4video.c
        ${libavcodec_c}/mpegaudiodata.c
        ${libavcodec_c}/ftr.c
        ${libavcodec_c}/simple_idct.c
        ${libavcodec_c}/svq3.c
        ${libavcodec_c}/vp9_superframe_bsf.c
        ${libavcodec_c}/dv.c
        ${libavcodec_c}/mlp_parse.c
        ${libavcodec_c}/htmlsubtitles.c
        ${libavcodec_c}/ftr_parser.c
        ${libavcodec_c}/extract_extradata_bsf.c
        ${libavcodec_c}/vp9_parser.c
        ${libavcodec_c}/jacosubdec.c
        ${libavcodec_c}/tpeldsp.c
        ${libavcodec_c}/adpcm_data.c
        ${libavcodec_c}/mqcdec.c
        ${libavcodec_c}/hqx.c
        ${libavcodec_c}/ylc.c
        ${libavcodec_c}/sanm.c
        ${libavcodec_c}/cook.c
        ${libavcodec_c}/dvbsubdec.c
        ${libavcodec_c}/qdrw.c
        ${libavcodec_c}/raw.c
        ${libavcodec_c}/apac.c
        ${libavcodec_c}/jpeg2000_parser.c
        ${libavcodec_c}/cbrt_data_fixed.c
        ${libavcodec_c}/h264data.c
        ${libavcodec_c}/targa_y216dec.c
        ${libavcodec_c}/g729_parser.c
        ${libavcodec_c}/ttadata.c
        ${libavcodec_c}/bitstream_filters.c
        ${libavcodec_c}/indeo2.c
        ${libavcodec_c}/evrcdec.c
        ${libavcodec_c}/xl.c
        ${libavcodec_c}/flacdata.c
        ${libavcodec_c}/g723_1dec.c
        ${libavcodec_c}/fmvc.c
        ${libavcodec_c}/siren.c
        ${libavcodec_c}/vp3_parser.c
        ${libavcodec_c}/hevc_mp4toannexb_bsf.c
        ${libavcodec_c}/hevc_mvs.c
        ${libavcodec_c}/png_parser.c
        ${libavcodec_c}/ra144dec.c
        ${libavcodec_c}/vvc_mp4toannexb_bsf.c
        ${libavcodec_c}/rtjpeg.c
        ${libavcodec_c}/mimic.c
        ${libavcodec_c}/on2avcdata.c
        ${libavcodec_c}/vulkan_video.c
        ${libavcodec_c}/ac3.c
        ${libavcodec_c}/cavsdata.c
        ${libavcodec_c}/vp8dsp.c
        ${libavcodec_c}/h261_parser.c
        ${libavcodec_c}/m101.c
        ${libavcodec_c}/vmdaudio.c
        ${libavcodec_c}/asvdec.c
        ${libavcodec_c}/h264_mp4toannexb_bsf.c
        ${libavcodec_c}/vvc_parser.c
        ${libavcodec_c}/h264_parser.c
        ${libavcodec_c}/fic.c
        ${libavcodec_c}/flac_parser.c
        ${libavcodec_c}/osq.c
        ${libavcodec_c}/qtrle.c
        ${libavcodec_c}/hq_hqa.c
        ${libavcodec_c}/on2avc.c
        ${libavcodec_c}/amr_parser.c
        ${libavcodec_c}/vp9recon.c
        ${libavcodec_c}/mlpdsp.c
)

set(avdevice_c
        ${libavdevice_c}/version.c
        ${libavdevice_c}/alldevices.c
        ${libavdevice_c}/utils.c
        ${libavdevice_c}/avdevice.c
)

add_library(avdevice ${avdevice_c})
add_library(avcodec ${avcodec_c} ${avcodec_asm})
add_library(avformat ${avformat_c})
add_library(avutil ${avutil_c} ${avutil_asm})

target_include_directories(avdevice PRIVATE ${libavdevice_c} ${ffmpeg_src})
target_include_directories(avcodec PRIVATE ${libavcodec_c}  ${ffmpeg_src})
target_include_directories(avutil PRIVATE ${libavutil_c} ${ffmpeg_src})
target_include_directories(avformat PRIVATE ${libavformat_c} ${ffmpeg_src})

