int main ();
size_t get_filesize (const char* filename);
void destroy_mmap ();
void init_mmap (const char* filename);
void destroy_collect_packet_headers ();
void init_collect_packet_headers ();
void init_process_packet_headers ();
void init_sequential_bit_function (sequential_bit_t* seq_state, size_t byte_pos);
inline bool get_sequential_bit (sequential_bit_t* seq_state);
int get_brc (sequential_bit_t* s);
void init_decode_packet (int packet_idx);
