#!/usr/bin/env python3
"""Bake real-world Earth data into a Lisp data file for the GLSL shader generator.

Outputs `earth_data.lisp` containing four packed uint32 tables:

  *land-mask-words*  256 x 128, 2 bits per cell  -> sub-cell land coverage (0..3)
  *coast-words*       64 x  32, 4 bits per cell  -> gaussian-blurred land coverage
                                                    (continental shelf / coastal water)
  *albedo-words*      64 x  32, RGB565, 2 cells per word -> land albedo
  *lights-words*      64 x  32, 4 bits per cell  -> night-time light emission

Total: 2048 + 256 + 1024 + 256 = 3584 uint32 (14 KB).  This must stay below the
NVIDIA GL limit for dynamically indexed const arrays (16 KB measured on an
RTX A4000, driver 610.57.04) or the shader fails to link with error C5041.

Sources (cached in tools/cache/):
  - Natural Earth 110m land polygons (public domain)   -> land mask + coast field
  - NASA Blue Marble "land_shallow_topo_2048"          -> land albedo
  - NASA "Earth's City Lights"                         -> night lights
"""

import json
import os
import sys
import urllib.request

import numpy as np
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, "cache")
OUT = os.path.join(os.path.dirname(HERE), "earth_data.lisp")

SOURCES = {
    "ne_110m_land.geojson": "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson",
    "blue_marble.jpg": "https://eoimages.gsfc.nasa.gov/images/imagerecords/57000/57752/land_shallow_topo_2048.jpg",
    "night_lights.jpg": "https://eoimages.gsfc.nasa.gov/images/imagerecords/55000/55167/earth_lights_lrg.jpg",
}

MASK_W, MASK_H = 256, 128
COAST_W, COAST_H = 64, 32
ALB_W, ALB_H = 64, 32
LIT_W, LIT_H = 64, 32


def fetch(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        print(f"  downloading {name} ...")
        req = urllib.request.Request(SOURCES[name], headers={"User-Agent": "earth-shader-baker/1.0"})
        with urllib.request.urlopen(req, timeout=120) as r, open(path, "wb") as f:
            f.write(r.read())
    print(f"  {name}: {os.path.getsize(path)} bytes")
    return path


def rasterize_land(geojson_path, w, h, supersample=8):
    """Rasterize land polygons into an equirectangular coverage map in [0,1]."""
    W, H = w * supersample, h * supersample
    img = Image.new("L", (W, H), 0)
    drw = ImageDraw.Draw(img)

    def project(ring):
        return [(((lon + 180.0) / 360.0) * W, ((90.0 - lat) / 180.0) * H) for lon, lat in ring]

    def draw_polygon(rings):
        drw.polygon(project(rings[0]), fill=255)
        for hole in rings[1:]:                      # interior rings (lakes) -> water
            drw.polygon(project(hole), fill=0)

    data = json.load(open(geojson_path))
    for feat in data["features"]:
        geom = feat["geometry"]
        if geom["type"] == "Polygon":
            draw_polygon(geom["coordinates"])
        elif geom["type"] == "MultiPolygon":
            for poly in geom["coordinates"]:
                draw_polygon(poly)

    arr = np.asarray(img, dtype=np.float32) / 255.0
    return arr.reshape(h, supersample, w, supersample).mean(axis=(1, 3))


def equirect_cells(img_path, w, h):
    im = Image.open(img_path).convert("RGB").resize((w, h), Image.BOX)
    return np.asarray(im, dtype=np.float32) / 255.0


def pack_fields(vals, bits):
    """vals: (h,w) integers -> uint32 words, `32/bits` cells per word, LSB first."""
    per = 32 // bits
    flat = vals.reshape(-1).astype(np.uint32)
    words = np.zeros((flat.size + per - 1) // per, dtype=np.uint64)
    for i, v in enumerate(flat):
        words[i // per] |= np.uint64(int(v) & ((1 << bits) - 1)) << np.uint64((i % per) * bits)
    return [int(x) for x in words]


def gaussian_blur_equirect(field, sigma_cells, radius):
    k = np.exp(-0.5 * (np.arange(-radius, radius + 1) / sigma_cells) ** 2)
    k /= k.sum()
    out = np.zeros_like(field)
    for i, w in enumerate(k):                                  # longitude wraps
        out += w * np.roll(field, i - radius, axis=1)
    padded = np.pad(out, ((radius, radius), (0, 0)), mode="edge")   # latitude clamps
    return sum(w * padded[i:i + field.shape[0]] for i, w in enumerate(k))


def write_lisp(path, tables):
    def emit_words(f, name, words, per_line=8):
        f.write(f"(defparameter {name}\n  (list\n")
        for i in range(0, len(words), per_line):
            f.write("   " + " ".join(f"#x{w:08x}" for w in words[i:i + per_line]) + "\n")
        f.write("   ))\n\n")

    with open(path, "w") as f:
        f.write(";;;; AUTO-GENERATED by tools/bake_earth_data.py -- do not edit by hand.\n")
        f.write(";;;; Real-world Earth data baked for the GLSL earth shader (gen4.lisp).\n")
        f.write(";;;;   land mask : Natural Earth 110m land polygons, 2 bit coverage\n")
        f.write(";;;;   coast     : gaussian-blurred land coverage, 4 bit\n")
        f.write(";;;;   albedo    : NASA Blue Marble land_shallow_topo_2048, RGB565\n")
        f.write(";;;;   lights    : NASA Earth's City Lights, 4 bit\n\n")
        f.write("(in-package :cl-cpp-generator2)\n\n")
        for name, val in (("*land-mask-w*", MASK_W), ("*land-mask-h*", MASK_H),
                          ("*coast-w*", COAST_W), ("*coast-h*", COAST_H),
                          ("*albedo-w*", ALB_W), ("*albedo-h*", ALB_H),
                          ("*lights-w*", LIT_W), ("*lights-h*", LIT_H)):
            f.write(f"(defparameter {name} {val})\n")
        f.write("\n")
        for name, words, per_line in tables:
            emit_words(f, name, words, per_line)


def main():
    print("Fetching source data:")
    geo = fetch("ne_110m_land.geojson")
    bm = fetch("blue_marble.jpg")
    lights = fetch("night_lights.jpg")

    print("Rasterizing land mask (2 bit sub-cell coverage) ...")
    cover = rasterize_land(geo, MASK_W, MASK_H)
    lat_w = np.cos(np.deg2rad(np.linspace(90, -90, MASK_H)))[:, None]
    frac = float((cover * lat_w).sum() / (lat_w * np.ones((1, MASK_W))).sum())
    print(f"  land fraction (area weighted): {frac:.3f} (Earth ~0.29)")
    mask_words = pack_fields(np.clip(cover * 3.0 + 0.5, 0, 3).astype(np.uint32), 2)

    print("Baking smooth coast field ...")
    cover_c = rasterize_land(geo, COAST_W, COAST_H, supersample=24)
    blur = gaussian_blur_equirect(cover_c, sigma_cells=1.0, radius=3)
    coast = np.clip(blur * 1.25, 0.0, 1.0)
    print(f"  coast field: mean {coast.mean():.3f} max {coast.max():.3f}")
    coast_words = pack_fields((coast * 15.0 + 0.5).astype(np.uint32), 4)

    print("Baking land albedo from Blue Marble (RGB565) ...")
    bm_cells = equirect_cells(bm, ALB_W, ALB_H)
    cover_a = rasterize_land(geo, ALB_W, ALB_H, supersample=24)
    # Ocean cells carry Blue-Marble ocean blue; the shader computes ocean colour
    # analytically, so flood-fill land colours outward to keep the bilinear
    # lookup free of blue bleed along the coastlines.
    wgt = np.clip((cover_a - 0.15) / 0.5, 0.0, 1.0)[..., None]
    col = bm_cells * wgt
    for _ in range(24):
        num = np.zeros_like(col)
        den = np.zeros_like(wgt)
        for dy, dx in ((-1, 0), (1, 0), (0, -1), (0, 1)):
            num += np.roll(np.roll(col, dy, axis=0), dx, axis=1)
            den += np.roll(np.roll(wgt, dy, axis=0), dx, axis=1)
        grow = (den > 0.0).astype(np.float32)
        fill = np.where(den > 0.0, num / np.maximum(den, 1e-6), 0.0)
        blend = np.clip(1.0 - wgt, 0.0, 1.0)
        col = col + fill * blend * grow
        wgt = np.clip(wgt + grow * blend, 0.0, 1.0)
    alb = np.clip(col / np.maximum(wgt, 1e-6), 0.0, 1.0)
    r5 = (alb[..., 0] * 31.0 + 0.5).astype(np.uint32)
    g6 = (alb[..., 1] * 63.0 + 0.5).astype(np.uint32)
    b5 = (alb[..., 2] * 31.0 + 0.5).astype(np.uint32)
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    alb_words = pack_fields(rgb565, 16)

    print("Baking night lights ...")
    lit_full = np.asarray(Image.open(lights).convert("RGB"), dtype=np.float32) / 255.0
    # City lights are warm (R,G high) over a dark blue backdrop: subtract blue.
    r, g, b = lit_full[..., 0], lit_full[..., 1], lit_full[..., 2]
    emis = np.clip(0.5 * (r + g) - 0.85 * b, 0.0, 1.0)
    fh, fw = emis.shape
    by, bx = fh // LIT_H, fw // LIT_W
    emis = emis[:by * LIT_H, :bx * LIT_W].reshape(LIT_H, by, LIT_W, bx).mean(axis=(1, 3))
    norm = np.percentile(emis, 99.5)
    lum = np.clip(emis / max(norm, 1e-4), 0.0, 1.0) ** 0.55
    lum[lum < 0.15] = 0.0                     # kill JPEG speckle over the oceans
    print(f"  lights: p99.5 {norm:.4f} lit cells {int((lum > 0.1).sum())}")
    lit_words = pack_fields((lum * 15.0 + 0.5).astype(np.uint32), 4)

    tables = [("*land-mask-words*", mask_words, 8),
              ("*coast-words*", coast_words, 8),
              ("*albedo-words*", alb_words, 8),
              ("*lights-words*", lit_words, 8)]
    total = sum(len(w) for _, w, _ in tables)
    print(f"  words: mask {len(mask_words)}, coast {len(coast_words)}, "
          f"albedo {len(alb_words)}, lights {len(lit_words)} -> total {total} "
          f"({total * 4 / 1024:.1f} KB, GPU limit 16 KB)")
    assert total < 4000, "const data too large for the driver's constant bank"

    write_lisp(OUT, tables)
    print(f"Wrote {OUT} ({os.path.getsize(OUT)} bytes)")


if __name__ == "__main__":
    sys.exit(main())
