(eval-when (:compile-toplevel :execute :load-toplevel)
  (ql:quickload "cl-cpp-generator2"))

(in-package :cl-cpp-generator2)

(progn
  (defparameter *code-file* (asdf:system-relative-pathname 'cl-cpp-generator2 "example/197_shadertoy/vulkan-shadertoy-x11/launcher/shaders/shadertoy/main_image.glsl"))
  (ensure-directories-exist *code-file*)
  (let* ((code
          `(do0
            "// --- transpiled raymarching shader with smin and shadows ---"
            (defun smin (a b k)
              (declare (type float a b k)
                       (values float))
              (let (h)
                (declare (type float h))
                (setf h (clamp (+ 0.5f0 (* 0.5f0 (/ (- b a) k))) 0.0f0 1.0f0))
                (return (- (mix b a h) (* k h (- 1.0f0 h))))))

            (defun sdSphere (p s)
              (declare (type vec3 p)
                       (type float s)
                       (values float))
              (return (- (length p) s)))

            (defun sdBox (p b)
              (declare (type vec3 p)
                       (type vec3 b)
                       (values float))
              (let (q)
                (declare (type vec3 q))
                (setf q (- (abs p) b))
                (return (+ (length (max q 0.0f0)) (min (max q.x (max q.y q.z)) 0.0f0)))))

            (defun map (p)
              (declare (type vec3 p)
                       (values float))
              (let (plane c s rot pRot box sphere blendedObject)
                (declare (type float plane c s blendedObject box sphere)
                         (type mat3 rot)
                         (type vec3 pRot))
                (setf plane (+ p.y 1.0f0)
                      c (cos iTime)
                      s (sin iTime)
                      rot (mat3 c 0.0f0 s 0.0f0 1.0f0 0.0f0 (- s) 0.0f0 c)
                      pRot (* rot p)
                      box (sdBox pRot (vec3 0.6f0))
                      sphere (sdSphere (- pRot (vec3 0.0f0 0.2f0 0.0f0)) 0.75f0)
                      blendedObject (smin box sphere 0.2f0))
                (return (min plane blendedObject))))

            (defun getNormal (p)
              (declare (type vec3 p)
                       (values vec3))
              (let (e d n)
                (declare (type vec2 e)
                         (type float d)
                         (type vec3 n))
                (setf e (vec2 0.001f0 0.0f0)
                      d (map p)
                      n (- d (vec3 (map (- p e.xyy))
                                   (map (- p e.yxy))
                                   (map (- p e.yyx)))))
                (return (normalize n))))

            (defun getShadow (ro rd mint maxt k)
              (declare (type vec3 ro rd)
                       (type float mint maxt k)
                       (values float))
              (let (res tVal)
                (declare (type float res tVal))
                (setf res 1.0f0
                      tVal mint)
                (for ("int i = 0" (< i 32) (incf i))
                  (let (h)
                    (declare (type float h))
                    (setf h (map (+ ro (* tVal rd))))
                    (when (< h 0.001f0)
                      (return 0.0f0))
                    (setf res (min res (/ (* k h) tVal)))
                    (incf tVal (clamp h 0.01f0 0.2f0))
                    (when (> tVal maxt)
                      break)))
                (return (clamp res 0.0f0 1.0f0))))

            (defun mainImage (fragColor fragCoord)
              (declare (type "out vec4" fragColor)
                       (type "in vec2" fragCoord)
                       (values void))
              (let (uv ro rd tVal maxDist hit p n lightPos l dif shadow objectColor col)
                (declare (type vec2 uv)
                         (type vec3 ro rd p n lightPos l objectColor col)
                         (type float tVal maxDist dif shadow)
                         (type bool hit))
                (setf uv (/ (- fragCoord (* 0.5f0 iResolution.xy)) iResolution.y)
                      ro (vec3 0.0f0 1.0f0 -3.0f0)
                      rd (normalize (vec3 uv 1.0f0))
                      tVal 0.0f0
                      maxDist 10.0f0
                      hit false)
                (for ("int i = 0" "i < 80" "i++")
                  (let (d)
                    (declare (type float d))
                    (setf d (map (+ ro (* tVal rd))))
                    (when (< d 0.001f0)
                      (setf hit true)
                      break)
                    (incf tVal d)
                    (when (> tVal maxDist)
                      break)))
                (setf col (vec3 0.1f0 0.15f0 0.2f0))
                (when hit
                  (setf p (+ ro (* tVal rd))
                        n (getNormal p)
                        lightPos (vec3 2.0f0 4.0f0 -1.0f0)
                        l (normalize (- lightPos p))
                        dif (clamp ("dot" n l) 0.0f0 1.0f0)
                        shadow (getShadow (+ p (* n 0.01f0)) l 0.01f0 5.0f0 16.0f0))
                  (if (> p.y -0.99f0)
                      (setf objectColor (vec3 0.9f0 0.4f0 0.1f0))
                      (setf objectColor (vec3 0.5f0)))
                  (setf col (* objectColor (+ (* dif shadow) 0.1f0))
                        col (pow col (vec3 0.4545f0))))
                (setf fragColor (vec4 col 1.0f0)))))))
    (write-source *code-file* code :format nil :tidy nil)))
