mkdir b
cd b
cmake -G Ninja \
 -DCMAKE_BUILD_TYPE=Release \
 -DENABLE_RYZEN_TESTS=ON \
 -DBUILD_EXAMPLE=OFF \
 -DBUILD_GMOCK=OFF \
 -DBUILD_TESTS=OFF \
 -DGLFW_BUILD_WAYLAND=OFF \
 -DDEP_DIR=/home/kiel/src \
 -DCMAKE_UNITY_BUILD=ON \
 -DCMAKE_UNITY_BUILD_MODE=GROUP \
 -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
 ..
