;;;; Generate SUPPORTED_FORMS.md from the executed test tables.
;;;;
;;;; Used via ./t/generate_docs.sh [--check]. Loading this file runs both
;;;; suites first (t/02 fully, t/03 fully); each quits nonzero on failure,
;;;; so the document can never be generated from failing tests.
;;;; Live re-emission (not the pinned reference strings) is printed,
;;;; exactly like cl-rust-generator::generate-documentation does it.

(eval-when (:compile-toplevel :execute :load-toplevel)
  (ql:quickload "cl-cpp-generator2" :silent t)
)

(in-package :cl-cpp-generator2)

(load (asdf:system-relative-pathname
        'cl-cpp-generator2 "t/02_paren_precedence/paren-tests.lisp"))
(load (asdf:system-relative-pathname
        'cl-cpp-generator2 "t/03_lambda/lambda-tests.lisp"))

(defun emit-with-omit (code omit)
  "Emit CODE the t/02 way. A local helper: t/02 and t/03 both define an
incompatible emit-str, so the shared generator calls emit-c directly."
  (m-of (emit-c :code code :omit-redundant-parentheses omit))
)

(defun write-expr-entry (s e)
  (destructuring-bind (&key name code omit full value description) e
    (declare (ignore omit))
    (format s "### ~a~%~%" name)
    (when description
      (format s "~a~%~%" description))
    (format s "```lisp~%~S~%```~%~%" code)
    (format s "Elided (`:omit-parens t`):~%```cpp~%~a~%```~%~%"
      (emit-with-omit code t))
    (when full
      (format s "Fully parenthesized:~%```cpp~%~a~%```~%~%"
        (emit-with-omit code nil)))
    (when value
      (format s "Evaluates to `~a`.~%~%" value)))
)

(defun write-lambda-entry (s e)
  (destructuring-bind (&key name code expected call value direct check void description) e
    (declare (ignore expected void))
    (format s "### ~a~%~%" name)
    (when description
      (format s "~a~%~%" description))
    (format s "```lisp~%~S~%```~%~%" code)
    (format s "```cpp~%~a~%```~%~%"
      (normalize (m-of (emit-c :code code))))
    (cond (check
            (format s "Verified by the custom condition `~a`.~%~%" check))
      (direct
        (format s "The complete expression evaluates to `~a`.~%~%" value))
      (t
        (format s "Called as `f~a` it evaluates to `~a`.~%~%" call value))))
)

(defun write-error-entry (s e)
  (destructuring-bind (&key name code error description) e
    (format s "### ~a~%~%" name)
    (when description
      (format s "~a~%~%" description))
    (format s "```lisp~%~S~%```~%~%" code)
    (format s "Signals an error containing `~a`.~%~%" error))
)

(defun write-docs (path)
  (let ((*print-case* :downcase)
        (*package* (find-package :cl-cpp-generator2)))
    (with-open-file (s path :direction :output :if-exists :supersede
                      :if-does-not-exist :create)
      (format s "# Supported S-Expression Forms~%~%")
      (format s "Auto-generated by `./t/generate_docs.sh` from the executed test tables in `t/02_paren_precedence/` and `t/03_lambda/`. Do not edit by hand.~%~%")
      (format s "Every example below is an executed test case: the Lisp form really does produce the C++ next to it. Both suites run before this file is written, so it can never be generated from failing tests. Cases without a prose description are covered by their name, forms and outputs alone; descriptions are added to the tables as they are written.~%~%")
      (format s "## Contents~%~%")
      (format s "- [Parenthesis elision](#parenthesis-elision)~%")
      (format s "- [Lambda emission](#lambda-emission)~%")
      (format s "- [Lambda errors](#lambda-errors)~%~%")
      (format s "## Parenthesis elision~%~%")
      (format s "~a cases from `t/02_paren_precedence/paren-tests.lisp`. Value tests use `int a = 7, b = 3, c = 2, d = 5;` and `int arr[8] = {10, 20, ..., 80};` (see `*variables*` there).~%~%"
        (length *expression-tests*))
      (dolist (e *expression-tests*)
        (write-expr-entry s e))
      (format s "## Lambda emission~%~%")
      (format s "~a cases from `t/03_lambda/lambda-tests.lisp`. Value tests use `int x = 5; int y = 7;`.~%~%"
        (length *lambda-tests*))
      (dolist (e *lambda-tests*)
        (write-lambda-entry s e))
      (format s "## Lambda errors~%~%")
      (dolist (e *lambda-error-tests*)
        (write-error-entry s e))))
  path
)
