// =================================================================
// EARTH GLOBE -- shared math (generated by gen4.lisp, do not edit)
// =================================================================
const float PI = 3.14159265359;
const int MARKER_N = 6;
const float MARKER_NF = 6.0;
const float TOUR_SEG = 4.00; // seconds spent per marker;
const float EARTH_R = 1.0;
const float CLOUD_R = 1.018;
// --- layout of the baked Earth data inside the state buffer -----------
// The GL driver turns big dynamically indexed const uint[] tables into
// uncached memory traffic (measured 19.5 ms vs 2.3 ms per 1080p frame),
// so buf0 unpacks them once per frame into its RGBA32F texture and the
// render pass reads them with texelFetch instead.
const int LAND_W = 256; // 2 bit land coverage, 1 cell per texel;
const int LAND_H = 128;
const int SMALL_W = 64; // coast / albedo / lights grids;
const int SMALL_H = 32;
const int LAND_Y = 4;    // land block occupies rows 4..131
const int SMALL_Y = 136; // small blocks occupy rows 136..167
const int COAST_X = 0;
const int ALB_X = 70;
const int LIT_X = 140;
// -> the state buffer must be at least 256 x 168 texels
// --- quaternion algebra (x,y,z = vector part, w = scalar) ---

vec4 qMul(vec4 a, vec4 b) {
  return vec4(a.w * b.xyz + b.w * a.xyz + cross(a.xyz, b.xyz),
              (a.w * b.w) - dot(a.xyz, b.xyz));
}

vec4 qConj(vec4 q) { return vec4(-q.xyz, q.w); }

vec3 qRot(vec4 q, vec3 v) {
  return v + 2.0F * cross(q.xyz, cross(q.xyz, v) + q.w * v);
}

vec4 qAxisAngle(vec3 ax, float ang) {
  return vec4(normalize(ax) * sin(0.50F * ang), cos(0.50F * ang));
}

vec4 qSlerp(vec4 a, vec4 b, float s) {
  float d = dot(a, b);
  if (d < 0.F) {
    b = -b;
    d = -d;
  }
  if (d > 0.99950F) {
    return normalize(mix(a, b, s));
  }
  float th0 = acos(clamp(d, -1.0F, 1.0F));
  float th = 0.F;
  th = th0 * s;
  return normalize(a * (sin(th0 - th) / sin(th0)) + b * (sin(th) / sin(th0)));
}

// --- marker table (cities, generated from the Lisp *markers* list) ---

vec3 markerDir(int i) {
  if (i == 0) {
    return vec3(0.14106666F, 0.7935658F, 0.5919067F);
  }
  if (i == 1) {
    return vec3(-0.7286451F, 0.652270F, 0.2088531F);
  }
  if (i == 2) {
    return vec3(-0.6302457F, -0.38923648F, 0.6717777F);
  }
  if (i == 3) {
    return vec3(0.26224550F, -0.5581072F, 0.7872379F);
  }
  if (i == 4) {
    return vec3(0.5259458F, 0.5832010F, -0.6190780F);
  }
  if (i == 5) {
    return vec3(0.39989248F, -0.5572959F, -0.7276725F);
  }
  return vec3(0.F, 0.F, 1.0F);
}

vec3 markerCol(int i) {
  if (i == 0) {
    return vec3(1.0F, 0.860F, 0.30F);
  }
  if (i == 1) {
    return vec3(0.350F, 0.90F, 1.0F);
  }
  if (i == 2) {
    return vec3(0.550F, 1.0F, 0.550F);
  }
  if (i == 3) {
    return vec3(1.0F, 0.550F, 0.750F);
  }
  if (i == 4) {
    return vec3(1.0F, 0.450F, 0.350F);
  }
  if (i == 5) {
    return vec3(0.70F, 0.70F, 1.0F);
  }
  return vec3(1.0F, 1.0F, 1.0F);
}

// Camera orientations solved in Lisp: qRot(q, markerDir(i)) == (0,0,1)

vec4 markerQuat(int i) {
  if (i == 0) {
    return vec4(0.4394214F, -0.10466866F, -5.163958e-2F, 0.8906664F);
  }
  if (i == 1) {
    return vec4(0.27780268F, 0.5642687F, 0.2093621F, 0.7487283F);
  }
  if (i == 2) {
    return vec4(-0.18464534F, 0.3605791F, -7.30559e-2F, 0.9113461F);
  }
  if (i == 3) {
    return vec4(-0.2879830F, -0.15312345F, 4.67050e-2F, 0.944160F);
  }
  if (i == 4) {
    return vec4(0.10564861F, -0.893520F, -0.28753160F, 0.32830864F);
  }
  if (i == 5) {
    return vec4(-7.241580e-2F, -0.9266025F, 0.2821329F, 0.23783351F);
  }
  return vec4(0.F, 0.F, 0.F, 1.0F);
}

// --- camera tour: dwell on a marker, then slerp to the next one ---

vec2 tourPhase(float tt) {
  float g = tt / TOUR_SEG;
  return vec2(floor(g), fract(g));
}

float tourEase(float ph) { return smoothstep(0.420F, 1.0F, ph); }

vec4 tourQuat(float tt) {
  vec2 seg = tourPhase(tt);
  int i0 = int(mod(seg.x, MARKER_NF));
  int i1 = int(mod(seg.x + 1.0F, MARKER_NF));
  float e = tourEase(seg.y);
  vec4 q = qSlerp(markerQuat(i0), markerQuat(i1), e);
  vec4 dq = qMul(
      qAxisAngle(vec3(0.F, 1.0F, 0.F), 3.50e-2F * sin(tt * 0.550F)),
      qAxisAngle(vec3(1.0F, 0.F, 0.F), 3.00e-2F * sin(tt * 0.370F + 1.10F)));
  return normalize(qMul(dq, q));
}

// (activeMarker marker, phase, camera distance, travel ease)

vec4 tourAux(float tt) {
  vec2 seg = tourPhase(tt);
  float e = tourEase(seg.y);
  return vec4(mod(seg.x, MARKER_NF), seg.y, 3.50F + 0.60F * sin(PI * e), e);
}
