(in-package :cl-cpp-generator2)

(write-source (format nil "~a/helpers.h" *full-source-dir*)
	      `(do0
		(pragma once)
		(include<> string vector algorithm cctype)
		(defun split_on_spaces (s)
		  (declare (type "const std::string&" s) (values "std::vector<std::string>"))
		  (let ((res (curly "std::vector<std::string>"))
			(token (string ""))
			(iss (space std--istringstream (paren s))))
		    (while (>> iss token)
			   (res.push_back token))
		    (return res)))
		(defun to_upper (s)
		  (declare (type "const std::string&" s) (values "std::string"))
		  (let ((upper s))
		    (std--transform (upper.begin) (upper.end) (upper.begin) (lambda (value) (declare (type "unsigned char" value)) (return (static_cast char (std--toupper value)))))
		    (return upper))))
	      :format t)

(write-source (format nil "~a/main.cpp" *full-source-dir*)
	      `(do0
		(include<> iostream string vector)
		(include "ForthVM.h")
		(namespace nil
			   (do0
			    (defun error_name (err)
			      (declare (type ForthVM--Error err) (values "const char*"))
			      (case err
				(ForthVM--kOk (return (string "kOk")))
				(ForthVM--Error--Stack_Underflow (return (string "Stack Underflow")))
				(ForthVM--Error--Stack_Overflow (return (string "Stack Overflow")))
				(ForthVM--Error--Dictionary_Full (return (string "Dictionary Full")))
				(ForthVM--Error--Compile_Error (return (string "Compile Error")))
				(ForthVM--Error--Invalid_Fuel (return (string "Invalid Fuel")))
				(t (return (string "Unknown Error")))))))
		(defun main ()
		  (declare (values int))
		  (let ((vm (new ForthVM))
			(line (string "")))
		    (while (std--getline std--cin line)
			   (handler-case
			       (vm->execute_line line)
			     (ForthVM--Error (error)
			       (when (!= error ForthVM--kOk)
				 (<< std--cerr (error_name error) (char "\\n"))))))
		    (delete vm)
		    (return 0))))
	      :format t)
