// =================================================================
// EARTH GLOBE -- render pass (generated by gen4.lisp)
// Baked datasets: Natural Earth 110m land, NASA Blue Marble albedo,
// NASA Earth's City Lights.  See tools/bake_earth_data.py
// =================================================================
// ------------- baked Earth data, read back from the state pass -------
// buf0 unpacked the tables into iChannel0 this frame; a texture read is
// an order of magnitude cheaper here than indexing a const uint array.

float landCov(int ix, int iy) {
  return texelFetch(
             iChannel0,
             ivec2((ix & (LAND_W - 1)), LAND_Y + clamp(iy, 0, LAND_H - 1)), 0)
      .x;
}

float coastTexel(int ix, int iy) {
  return texelFetch(iChannel0,
                    ivec2(COAST_X + ((ix & (SMALL_W - 1))),
                          SMALL_Y + clamp(iy, 0, SMALL_H - 1)),
                    0)
      .x;
}

vec3 albTexel(int ix, int iy) {
  return texelFetch(iChannel0,
                    ivec2(ALB_X + ((ix & (SMALL_W - 1))),
                          SMALL_Y + clamp(iy, 0, SMALL_H - 1)),
                    0)
      .xyz;
}

float litTexel(int ix, int iy) {
  return texelFetch(iChannel0,
                    ivec2(LIT_X + ((ix & (SMALL_W - 1))),
                          SMALL_Y + clamp(iy, 0, SMALL_H - 1)),
                    0)
      .x;
}

// bilinear land coverage in [0,1]; u wraps around the globe

float landField(vec2 uv) {
  float x = (fract(uv.x) * float(LAND_W)) - 0.50F;
  float y = (clamp(uv.y, 0.F, 1.0F) * float(LAND_H)) - 0.50F;
  int x0 = 0;
  int y0 = 0;
  float fx = 0.F;
  float fy = 0.F;
  x0 = int(floor(x));
  y0 = int(floor(y));
  fx = (x - float(x0));
  fy = (y - float(y0));
  return mix(mix(landCov(x0, y0), landCov(x0 + 1, y0), fx),
             mix(landCov(x0, y0 + 1), landCov(x0 + 1, y0 + 1), fx), fy);
}

// gaussian-blurred land coverage: 1 = deep inland, ~0.5 = coastline,
// 0 = open ocean.  Drives the continental shelf colour.

float coastField(vec2 uv) {
  float x = (fract(uv.x) * float(SMALL_W)) - 0.50F;
  float y = (clamp(uv.y, 0.F, 1.0F) * float(SMALL_H)) - 0.50F;
  int x0 = 0;
  int y0 = 0;
  float fx = 0.F;
  float fy = 0.F;
  x0 = int(floor(x));
  y0 = int(floor(y));
  fx = (x - float(x0));
  fy = (y - float(y0));
  fx = fx * fx * (3.0F - (2.0F * fx));
  fy = fy * fy * (3.0F - (2.0F * fy));
  return mix(mix(coastTexel(x0, y0), coastTexel(x0 + 1, y0), fx),
             mix(coastTexel(x0, y0 + 1), coastTexel(x0 + 1, y0 + 1), fx), fy);
}

vec3 albField(vec2 uv) {
  float x = (fract(uv.x) * float(SMALL_W)) - 0.50F;
  float y = (clamp(uv.y, 0.F, 1.0F) * float(SMALL_H)) - 0.50F;
  int x0 = 0;
  int y0 = 0;
  float fx = 0.F;
  float fy = 0.F;
  x0 = int(floor(x));
  y0 = int(floor(y));
  fx = (x - float(x0));
  fy = (y - float(y0));
  return mix(mix(albTexel(x0, y0), albTexel(x0 + 1, y0), fx),
             mix(albTexel(x0, y0 + 1), albTexel(x0 + 1, y0 + 1), fx), fy);
}

float litField(vec2 uv) {
  float x = (fract(uv.x) * float(SMALL_W)) - 0.50F;
  float y = (clamp(uv.y, 0.F, 1.0F) * float(SMALL_H)) - 0.50F;
  int x0 = 0;
  int y0 = 0;
  float fx = 0.F;
  float fy = 0.F;
  x0 = int(floor(x));
  y0 = int(floor(y));
  fx = (x - float(x0));
  fy = (y - float(y0));
  return mix(mix(litTexel(x0, y0), litTexel(x0 + 1, y0), fx),
             mix(litTexel(x0, y0 + 1), litTexel(x0 + 1, y0 + 1), fx), fy);
}

// --------------------------- noise --------------------------------

float hash31(vec3 p) {
  vec3 q = fract(p * 0.318310F + vec3(0.110F, 0.170F, 0.130F));
  q = q * 17.F;
  return fract(q.x * q.y * q.z * (q.x + q.y + q.z));
}

float vnoise(vec3 x) {
  vec3 i = floor(x);
  vec3 f = fract(x);
  f = f * f * (3.0F - (2.0F * f));
  return mix(mix(mix(hash31(i + vec3(0.F, 0.F, 0.F)),
                     hash31(i + vec3(1.0F, 0.F, 0.F)), f.x),
                 mix(hash31(i + vec3(0.F, 1.0F, 0.F)),
                     hash31(i + vec3(1.0F, 1.0F, 0.F)), f.x),
                 f.y),
             mix(mix(hash31(i + vec3(0.F, 0.F, 1.0F)),
                     hash31(i + vec3(1.0F, 0.F, 1.0F)), f.x),
                 mix(hash31(i + vec3(0.F, 1.0F, 1.0F)),
                     hash31(i + vec3(1.0F, 1.0F, 1.0F)), f.x),
                 f.y),
             f.z);
}

// Rotating every octave breaks the axis aligned value noise lattice
// (otherwise the deserts show a corduroy pattern at high resolution).
const mat3 NROT =
    mat3(0.00, 0.80, 0.60, -0.80, 0.36, -0.48, -0.60, -0.48, 0.64);
// fractal brownian motion, result roughly in [0,1]

float fbmN(vec3 p, int oct) {
  float a = 0.50F;
  float s = 0.F;
  vec3 q = p;
  for (int i = 0; i < 8; i++) {
    if (i >= oct) {
      break;
    }
    s += a * vnoise(q);
    q = NROT * q * 2.030F + vec3(1.70F, 9.20F, 3.30F);
    a = a * 0.50F;
  }
  return s;
}

// ridged multifractal -> mountain chains

float ridgedN(vec3 p, int oct) {
  float a = 0.50F;
  float s = 0.F;
  vec3 q = p;
  float n = 0.F;
  for (int i = 0; i < 8; i++) {
    if (i >= oct) {
      break;
    }
    n = ((2.0F * vnoise(q)) - 1.0F);
    s += a * (1.0F - abs(n));
    q = NROT * q * 2.110F + vec3(4.40F, 1.90F, 7.10F);
    a = a * 0.50F;
  }
  return s;
}

// ---------------------- geography helpers -------------------------
// earth-fixed direction -> equirectangular texture coordinate

vec2 dirToUV(vec3 d) {
  float lat = asin(clamp(d.y, -1.0F, 1.0F));
  float lon = atan(d.x, d.z + 1.00e-7F);
  return vec2((lon / (2.0F * PI)) + 0.50F, 0.50F - (lat / PI));
}

// terrain elevation proxy used for bump mapping and snow lines

float terrainH(vec3 ld) {
  return 0.550F * fbmN(ld * 3.40F, 4) +
         0.450F * ridgedN(ld * 11.F + vec3(3.10F, 0.70F, 5.30F), 5);
}

// animated cloud cover in [0,1]: large weather systems eroded by fine
// detail, drifting on latitude dependent jet streams.

float cloudAt(vec3 ld) {
  float lat = asin(clamp(ld.y, -1.0F, 1.0F));
  float lon = atan(ld.x, ld.z + 1.00e-7F);
  vec3 cd = vec3(0.F);
  vec3 w = vec3(0.F);
  float base = 0.F;
  float fine = 0.F;
  float wisp = 0.F;
  float cov = 0.F;
  float dens = 0.F;
  lon = lon + iTime * (1.20e-2F + 2.00e-2F * sin(lat * 5.0F));
  cd = vec3(cos(lat) * sin(lon), sin(lat), cos(lat) * cos(lon));
  w = (vec3(fbmN(cd * 2.20F + vec3(0.F, 0.F, iTime * 2.10e-2F), 3),
            fbmN(cd * 2.20F + vec3(5.20F, 1.30F, iTime * 1.90e-2F), 3),
            fbmN(cd * 2.20F + vec3(9.10F, 7.70F, iTime * 2.30e-2F), 3)) -
       0.50F);
  base = fbmN(cd * 3.60F + w * 1.50F + vec3(0.F, iTime * 1.20e-2F, 0.F), 5);
  fine = fbmN(cd * 14.F + w * 3.0F + vec3(iTime * 3.00e-2F, 0.F, 0.F), 4);
  wisp = fbmN(cd * 32.F + vec3(0.F, 0.F, iTime * 5.00e-2F), 3);
  cov = (0.5680F - (5.00e-2F * cos(lat * 6.20F)) - (3.00e-2F * sin(abs(lat))));
  dens = base + 0.20F * (fine - 0.50F);
  dens = smoothstep(cov, cov + 0.1550F, dens);
  dens = dens * (0.450F + 0.550F * fine) * (0.70F + 0.30F * wisp);
  return clamp(dens * 1.450F, 0.F, 1.0F);
}

// ---------------------- background star field ---------------------

vec3 starField(vec3 rd) {
  vec3 col = vec3(2.00e-3F, 3.50e-3F, 7.00e-3F);
  vec3 bandAxis = normalize(vec3(0.350F, 0.550F, -0.750F));
  float bd = 0.F;
  float sc = 0.F;
  vec3 g = vec3(0.F);
  vec3 id = vec3(0.F);
  vec3 fp = vec3(0.F);
  vec3 off = vec3(0.F);
  float h = 0.F;
  float dd = 0.F;
  float tw = 0.F;
  float tint = 0.F;
  bd = (dot(rd, bandAxis) / 0.330F);
  col += vec3(4.50e-2F, 4.00e-2F, 7.50e-2F) * exp(-bd * bd) *
         (0.350F + 0.650F * fbmN(rd * 5.0F, 4));
  for (int k = 0; k < 3; k++) {
    sc = 70.F * (1.0F + 1.350F * float(k));
    g = rd * sc;
    id = floor(g);
    fp = (fract(g) - 0.50F);
    h = hash31(id + 13.70F * float(k));
    if (h > 0.9450F) {
      off = (vec3(hash31(id + vec3(1.70F, 0.30F, 5.10F)),
                  hash31(id + vec3(3.30F, 8.20F, 1.90F)),
                  hash31(id + vec3(5.90F, 2.40F, 7.30F))) -
             0.50F);
      dd = length(fp - (off * 0.650F));
      tw = 0.550F + 0.450F * sin(iTime * 2.20F + h * 90.F);
      tint = hash31(id + vec3(0.50F, 0.50F, 0.50F));
      col += mix(vec3(0.650F, 0.780F, 1.0F), vec3(1.0F, 0.850F, 0.620F), tint) *
             exp(-9.00e+2F * dd * dd) * tw * 26.F * (h - 0.9450F);
    }
  }
  return col;
}

// ------------------- marker geometry helpers ----------------------
// closest distance between the view ray and the line segment [a,b]

float raySegDist(vec3 ro, vec3 rd, vec3 a, vec3 b) {
  vec3 v = b - a;
  vec3 w0 = ro - a;
  float a12 = 0.F;
  float a22 = 0.F;
  float b1 = 0.F;
  float b2 = 0.F;
  float det = 0.F;
  float s = 0.F;
  float tt = 0.F;
  vec3 pt = vec3(0.F);
  a12 = -dot(rd, v);
  a22 = dot(v, v);
  b1 = -dot(rd, w0);
  b2 = dot(v, w0);
  det = (a22 - (a12 * a12));
  if (det > 1.00e-6F) {
    s = ((b2 - (a12 * b1)) / det);
  }
  s = clamp(s, 0.F, 1.0F);
  pt = a + v * s;
  tt = max(dot(rd, pt - ro), 0.F);
  return length((ro + rd * tt) - pt);
}

// glowing rings painted onto the planet surface at every marker

vec3 markerSurface(vec3 ld, float active) {
  vec3 acc = vec3(0.F);
  vec3 mi = vec3(0.F);
  vec3 ci = vec3(0.F);
  float hi = 0.F;
  float ang = 0.F;
  float core = 0.F;
  float ph = 0.F;
  float halo = 0.F;
  float rr = 0.F;
  float e1 = 0.F;
  float e2 = 0.F;
  mi = vec3(0.14106666F, 0.7935658F, 0.5919067F);
  ci = vec3(1.0F, 0.860F, 0.30F);
  hi = abs(active - 0.F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  mi = vec3(-0.7286451F, 0.652270F, 0.2088531F);
  ci = vec3(0.350F, 0.90F, 1.0F);
  hi = abs(active - 1.0F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.170F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  mi = vec3(-0.6302457F, -0.38923648F, 0.6717777F);
  ci = vec3(0.550F, 1.0F, 0.550F);
  hi = abs(active - 2.0F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.340F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  mi = vec3(0.26224550F, -0.5581072F, 0.7872379F);
  ci = vec3(1.0F, 0.550F, 0.750F);
  hi = abs(active - 3.0F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.510F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  mi = vec3(0.5259458F, 0.5832010F, -0.6190780F);
  ci = vec3(1.0F, 0.450F, 0.350F);
  hi = abs(active - 4.0F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.680F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  mi = vec3(0.39989248F, -0.5572959F, -0.7276725F);
  ci = vec3(0.70F, 0.70F, 1.0F);
  hi = abs(active - 5.0F) < 0.50F ? 1.0F : 0.350F;
  ang = acos(clamp(dot(ld, mi), -1.0F, 1.0F));
  if (ang < 0.30F) {
    core = smoothstep(1.60e-2F, 7.00e-3F, ang);
    ph = fract((iTime * 0.550F) - 0.850F);
    halo = 0.550F * exp(-9.00e+2F * ang * ang);
    rr = 2.20e-2F + ph * 0.1550F;
    e1 = ((ang - rr) / 7.50e-3F);
    e2 = ((ang - 3.00e-2F) / 4.50e-3F);
    acc += ci * hi *
           (core * 4.0F + halo + 2.0F * exp(-e1 * e1) * (1.0F - ph) +
            1.10F * exp(-e2 * e2) * (0.550F + 0.450F * sin(iTime * 3.0F)));
  }
  return acc;
}

// vertical light beams standing on the markers

vec3 markerBeams(vec3 ro, vec3 rd, vec4 q, float active) {
  vec3 acc = vec3(0.F);
  vec3 wp = vec3(0.F);
  vec3 ci = vec3(0.F);
  float hi = 0.F;
  float facing = 0.F;
  float vis = 0.F;
  float top = 0.F;
  float dseg = 0.F;
  wp = qRot(q, vec3(0.14106666F, 0.7935658F, 0.5919067F));
  ci = vec3(1.0F, 0.860F, 0.30F);
  hi = abs(active - 0.F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  wp = qRot(q, vec3(-0.7286451F, 0.652270F, 0.2088531F));
  ci = vec3(0.350F, 0.90F, 1.0F);
  hi = abs(active - 1.0F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  wp = qRot(q, vec3(-0.6302457F, -0.38923648F, 0.6717777F));
  ci = vec3(0.550F, 1.0F, 0.550F);
  hi = abs(active - 2.0F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  wp = qRot(q, vec3(0.26224550F, -0.5581072F, 0.7872379F));
  ci = vec3(1.0F, 0.550F, 0.750F);
  hi = abs(active - 3.0F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  wp = qRot(q, vec3(0.5259458F, 0.5832010F, -0.6190780F));
  ci = vec3(1.0F, 0.450F, 0.350F);
  hi = abs(active - 4.0F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  wp = qRot(q, vec3(0.39989248F, -0.5572959F, -0.7276725F));
  ci = vec3(0.70F, 0.70F, 1.0F);
  hi = abs(active - 5.0F) < 0.50F ? 1.0F : 0.40F;
  facing = dot(normalize(ro - wp), wp);
  if (facing > 2.00e-2F) {
    vis = smoothstep(2.00e-2F, 0.250F, facing);
    top = 1.0F + 0.260F * hi;
    dseg = raySegDist(ro, rd, wp * 1.0010F, wp * top);
    acc += ci * hi * vis *
           (0.850F * exp(-1.80e+3F * dseg * dseg) +
            0.180F * exp(-1.60e+2F * dseg * dseg));
  }
  return acc;
}

// ---------------------------- HUD ---------------------------------

vec3 hudOverlay(vec2 suv, float active, float phase) {
  vec3 acc = vec3(0.F);
  vec2 p = vec2(suv.x * (iResolution.x / iResolution.y), suv.y);
  vec3 c = vec3(0.F);
  vec2 pc = vec2(0.F);
  float on = 0.F;
  float dd = 0.F;
  float play = 0.F;
  c = vec3(1.0F, 0.860F, 0.30F);
  pc = vec2(5.50e-2F, 5.50e-2F);
  on = abs(active - 0.F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  c = vec3(0.350F, 0.90F, 1.0F);
  pc = vec2(0.10F, 5.50e-2F);
  on = abs(active - 1.0F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  c = vec3(0.550F, 1.0F, 0.550F);
  pc = vec2(0.1450F, 5.50e-2F);
  on = abs(active - 2.0F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  c = vec3(1.0F, 0.550F, 0.750F);
  pc = vec2(0.190F, 5.50e-2F);
  on = abs(active - 3.0F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  c = vec3(1.0F, 0.450F, 0.350F);
  pc = vec2(0.2350F, 5.50e-2F);
  on = abs(active - 4.0F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  c = vec3(0.70F, 0.70F, 1.0F);
  pc = vec2(0.280F, 5.50e-2F);
  on = abs(active - 5.0F) < 0.50F ? 1.0F : 0.F;
  dd = length(p - pc);
  acc += c * (mix(0.20F, 1.0F, on) * smoothstep(8.00e-3F, 5.00e-3F, dd) +
              on * 0.30F * smoothstep(3.00e-2F, 1.10e-2F, dd) *
                  (0.450F + 0.550F * sin(iTime * 4.0F)));
  play = 5.50e-2F + 4.50e-2F * (active + phase);
  if (p.x > 5.00e-2F && p.x < 0.2850F && abs(p.y - 3.00e-2F) < 1.80e-3F) {
    acc += vec3(0.550F, 0.720F, 0.950F) * (p.x < play ? 0.80F : 0.130F);
  }
  return acc;
}

// ---------------------- planet surface shading --------------------

vec3 shadeSurface(vec3 ro, vec3 rd, float tHit, vec4 q, vec4 qi, vec3 sunDir,
                  float active) {
  vec3 pw = ro + rd * tHit;
  vec3 nw = vec3(0.F);
  vec3 ld = vec3(0.F);
  vec2 tuv = vec2(0.F);
  vec2 wuv = vec2(0.F);
  float lf = 0.F;
  float lb = 0.F;
  float cn = 0.F;
  float isLand = 0.F;
  float shelf = 0.F;
  float h0 = 0.F;
  float latAbs = 0.F;
  vec3 tu = vec3(0.F);
  vec3 tv = vec3(0.F);
  float eps = 3.50e-3F;
  float hu = 0.F;
  float hv = 0.F;
  float bump = 0.F;
  vec3 nl = vec3(0.F);
  vec3 nrm = vec3(0.F);
  vec3 nsea = vec3(0.F);
  float wob = 0.F;
  float wob2 = 0.F;
  vec3 lcol = vec3(0.F);
  vec3 ocol = vec3(0.F);
  vec3 alb = vec3(0.F);
  float snow = 0.F;
  float ice = 0.F;
  vec3 sunLocal = vec3(0.F);
  float cshadow = 1.0F;
  float ndl = 0.F;
  float gdl = 0.F;
  float wrap = 0.F;
  float day = 0.F;
  vec3 sunCol = vec3(1.0F, 0.9550F, 0.90F);
  vec3 hvec = vec3(0.F);
  float spec = 0.F;
  float lights = 0.F;
  float fres = 0.F;
  vec3 lit = vec3(0.F);
  nw = normalize(pw);
  ld = qRot(qi, nw);
  tuv = dirToUV(ld);
  wuv =
      tuv +
      vec2(7.00e-3F * (fbmN(ld * 6.50F, 3) - 0.50F),
           3.50e-3F * (fbmN(ld * 6.50F + vec3(5.0F, 1.0F, 3.0F), 3) - 0.50F)) +
      vec2(2.20e-3F * (fbmN(ld * 27.F, 2) - 0.50F),
           1.10e-3F * (fbmN(ld * 27.F + vec3(2.0F, 7.0F, 4.0F), 2) - 0.50F));
  lf = landField(wuv);
  lb = coastField(wuv);
  cn = (fbmN(ld * 26.F, 4) - 0.50F);
  isLand = smoothstep(0.440F, 0.560F, lf + 0.110F * cn);
  shelf = 0.90F * smoothstep(1.50e-2F, 0.420F, lb);
  h0 = 0.50F;
  latAbs = abs(ld.y);
  // tangent frame (robust at the poles) + wind ruffled water normal
  tu = normalize(cross(
      abs(ld.y) < 0.90F ? vec3(0.F, 1.0F, 0.F) : vec3(1.0F, 0.F, 0.F), ld));
  tv = cross(ld, tu);
  wob = (vnoise(ld * 2.60e+2F + vec3(0.F, iTime * 0.450F, 0.F)) - 0.50F);
  wob2 = (vnoise(ld * 4.30e+2F + vec3(iTime * 0.350F, 0.F, 0.F)) - 0.50F);
  nsea = normalize(nw + 2.20e-2F * qRot(q, tu * wob + tv * wob2));
  nl = ld;
  // terrain bump: differentiate the elevation proxy in the tangent
  // frame -- skipped over open water, which is most of the planet
  if (isLand > 2.00e-2F) {
    h0 = terrainH(ld);
    hu = terrainH(normalize(ld + tu * eps));
    hv = terrainH(normalize(ld + tv * eps));
    bump = 2.00e-2F * isLand;
    nl = normalize(ld - ((tu * (hu - h0) + tv * (hv - h0)) * (bump / eps)));
  }
  nrm = normalize(mix(nsea, normalize(qRot(q, nl)), isLand));
  // albedo: baked Blue Marble land colour, analytic ocean, snow & ice
  lcol = albField(tuv);
  lcol = lcol * lcol;
  lcol = lcol * (0.780F + 0.440F * fbmN(ld * 34.F, 3));
  snow = smoothstep(0.930F, 0.990F,
                    latAbs + 0.10F * (h0 - 0.50F) +
                        3.00e-2F * (fbmN(ld * 11.F, 3) - 0.50F));
  ice = smoothstep(0.9350F, 0.9850F,
                   latAbs + 5.00e-2F * (fbmN(ld * 17.F, 3) - 0.50F));
  lcol = mix(lcol, vec3(0.860F, 0.90F, 0.950F), snow);
  ocol = mix(vec3(6.00e-3F, 2.650e-2F, 7.30e-2F),
             vec3(3.00e-2F, 0.160F, 0.2150F), shelf * shelf);
  ocol = mix(ocol, vec3(0.720F, 0.80F, 0.860F), ice);
  alb = mix(ocol, lcol, isLand);
  // direct light, soft terminator, cloud shadow
  sunLocal = qRot(qi, sunDir);
  ndl = dot(nrm, sunDir);
  gdl = dot(nw, sunDir);
  if (gdl > -0.10F) {
    cshadow = (1.0F - (0.30F * cloudAt(normalize(ld + sunLocal * 3.00e-2F))));
  }
  wrap = clamp((ndl + 0.180F) / 1.180F, 0.F, 1.0F);
  day = smoothstep(-0.20F, 0.160F, gdl);
  sunCol = mix(vec3(1.0F, 0.620F, 0.340F), sunCol, smoothstep(0.F, 0.30F, gdl));
  lit = alb * sunCol * wrap * 1.050F * cshadow;
  lit += alb * vec3(3.00e-2F, 4.80e-2F, 8.50e-2F);
  // specular sun glint on open water
  hvec = normalize(sunDir - rd);
  spec = pow(clamp(dot(nsea, hvec), 0.F, 1.0F), 9.00e+2F);
  spec = spec * (0.550F +
                 0.90F * vnoise(ld * 9.00e+2F + vec3(0.F, iTime * 0.80F, 0.F)));
  lit += sunCol * spec * 1.250F * (1.0F - isLand) *
         smoothstep(0.F, 0.150F, gdl) * cshadow;
  // night side city lights: gated to the dark side, broken into clusters
  lights =
      smoothstep(0.220F, 0.80F, litField(tuv)) * isLand *
      pow(1.0F - day, 2.50F) *
      (0.120F + 1.150F * smoothstep(0.420F, 0.80F, fbmN(ld * 1.50e+2F, 2)));
  lit += vec3(1.0F, 0.70F, 0.360F) * lights * 1.60F *
         (0.880F + 0.120F * sin(iTime * 6.0F + 40.F * tuv.x));
  // atmospheric limb brightening on the disc
  fres = pow(1.0F - clamp(dot(nw, -rd), 0.F, 1.0F), 4.20F);
  lit += vec3(0.220F, 0.440F, 1.0F) * fres * (5.00e-2F + 0.950F * day) * 1.10F;
  lit += markerSurface(ld, active);
  return lit;
}

// ------------------------- cloud shell ----------------------------
// returns rgb in .xyz and coverage alpha in .w

vec4 shadeClouds(vec3 ro, vec3 rd, float bb, vec4 qi, vec3 sunDir) {
  float cc = dot(ro, ro) - (CLOUD_R * CLOUD_R);
  float d2 = 0.F;
  float ts = 0.F;
  vec3 ps = vec3(0.F);
  vec3 ns = vec3(0.F);
  float cld = 0.F;
  float cldSun = 0.F;
  float grz = 0.F;
  float path = 0.F;
  float gdl = 0.F;
  float alpha = 0.F;
  float dayc = 0.F;
  vec3 ccol = vec3(0.F);
  d2 = ((bb * bb) - cc);
  if (d2 < 0.F) {
    return vec4(0.F);
  }
  ts = (-bb - sqrt(d2));
  if (ts < 0.F) {
    return vec4(0.F);
  }
  ps = ro + rd * ts;
  ns = normalize(ps);
  cld = cloudAt(qRot(qi, ns));
  if (cld < 4.00e-3F) {
    return vec4(0.F);
  }
  grz = clamp(-dot(ns, -rd), 0.F, 1.0F);
  path = min(1.0F / max(grz, 0.380F), 1.70F);
  gdl = dot(ns, sunDir);
  alpha = min(cld * path * 0.80F, 0.940F);
  cldSun = cloudAt(qRot(qi, normalize(ns + sunDir * 3.50e-2F)));
  dayc = smoothstep(-0.220F, 0.160F, gdl);
  ccol = vec3(1.0F, 0.9850F, 0.960F) *
         (1.220F * clamp(gdl, 0.F, 1.0F) + 5.50e-2F) *
         (1.0F - (0.40F * cldSun));
  ccol += vec3(4.50e-2F, 7.50e-2F, 0.140F) * (1.0F - dayc);
  // grazing rays look through much more cloud and air: brighten towards
  // the limb so the shell silhouette blends into the atmosphere ring
  // instead of cutting a dark notch out of it
  ccol += vec3(0.420F, 0.60F, 1.0F) * pow(1.0F - grz, 3.0F) *
          (0.120F + 0.880F * dayc) * 1.150F;
  return vec4(ccol, alpha);
}

// ------------------- atmosphere halo outside the disc -------------

vec3 atmoHalo(vec3 ro, vec3 rd, float bb, vec3 sunDir) {
  float perp = 0.F;
  float hgt = 0.F;
  float g = 0.F;
  float sunSide = 0.F;
  vec3 nearDir = vec3(0.F);
  if (bb > 0.F) {
    return vec3(0.F);
  }
  perp = sqrt(max(dot(ro, ro) - (bb * bb), 0.F));
  if (perp < EARTH_R) {
    return vec3(0.F);
  }
  nearDir = normalize(ro + rd * -bb);
  hgt = (perp - EARTH_R);
  g = exp(-21.50F * hgt);
  sunSide = smoothstep(-0.350F, 0.60F, dot(nearDir, sunDir));
  return vec3(0.240F, 0.460F, 1.0F) * g * (6.00e-2F + 1.250F * sunSide) *
         0.950F;
}

// ========================== main image ===========================

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
  vec4 q = texelFetch(iChannel0, ivec2(0, 0), 0);
  vec4 aux = texelFetch(iChannel0, ivec2(1, 0), 0);
  vec4 qi = vec4(0.F);
  float camDist = 3.0F;
  float active = 0.F;
  float sunA = 0.F;
  vec2 uv = (fragCoord - (0.50F * iResolution.xy)) / iResolution.y;
  vec3 ro = vec3(0.F);
  vec3 rd = vec3(0.F);
  vec3 sunDir = vec3(0.F);
  vec3 col = vec3(0.F);
  float bb = 0.F;
  float cc = 0.F;
  float disc = 0.F;
  float tHit = -1.0F;
  float vig = 0.F;
  vec4 clouds = vec4(0.F);
  qi = qConj(q);
  camDist = max(aux.z, 2.20F);
  active = aux.x;
  ro = vec3(0.F, 0.F, camDist);
  rd = normalize(vec3(uv, -1.620F));
  sunA = 1.180F + 0.20F * sin(iTime * 5.00e-2F);
  sunDir = normalize(vec3(sin(sunA), 0.260F, cos(sunA)));
  bb = dot(ro, rd);
  cc = (dot(ro, ro) - (EARTH_R * EARTH_R));
  disc = ((bb * bb) - cc);
  if (disc > 0.F) {
    tHit = (-bb - sqrt(disc));
  }
  if (tHit > 0.F) {
    col = shadeSurface(ro, rd, tHit, q, qi, sunDir, active);
  } else {
    col = starField(rd);
  }
  clouds = shadeClouds(ro, rd, bb, qi, sunDir);
  col = mix(col, clouds.xyz, clouds.w);
  // the halo goes on top of the cloud shell, whose silhouette would
  // otherwise paint a dark ring across the blue limb glow
  if (tHit < 0.F) {
    col += atmoHalo(ro, rd, bb, sunDir);
  }
  col += markerBeams(ro, rd, q, active);
  // tone mapping, vignette, HUD
  col = max(col, vec3(0.F));
  col = col * 1.020F;
  col = (col / (vec3(1.0F) + col * 0.620F));
  col = pow(col, vec3(0.45450F));
  col = mix(vec3(dot(col, vec3(0.2990F, 0.5870F, 0.1140F))), col, 1.180F);
  col = max(col, vec3(0.F));
  vig = clamp(1.0F - (0.280F * dot(uv, uv)), 0.F, 1.0F);
  col = col * vig;
  col += hudOverlay(fragCoord / iResolution.xy, active, aux.y);
  // tiny dither so the smooth ramps do not band in 8 bit
  col += ((hash31(vec3(fragCoord, iTime * 60.F)) - 0.50F) / 255.F);
  fragColor = vec4(col, 1.0F);
}
