name: CMake Build Ryzen Monitor ImGui

on:
  push:
    branches: [ "master" ]
    paths:
      - 'example/143_ryzen_monitor/source01/**'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake ninja-build \
          clang libxrandr-dev libxinerama-dev \
          libxcursor-dev libxi-dev libgl1-mesa-dev 

    - name: Install GLFW dependency from repo
      run: |
        git clone --depth 1 https://github.com/glfw/glfw 
        du -hs glfw
        pwd

    - name: Install ImGui dependency from repo
      run: | 
        git clone --depth 1 https://github.com/ocornut/imgui 
        du -hs imgui
        pwd
        find `pwd`

    - name: Install ImPlot dependency from repo
      run: |
        git clone --depth 1 https://github.com/epezent/implot 
        du -hs implot
        pwd

    - name: Install ryzen_monitor dependency from repo
      run: |
        git clone --depth 1 https://github.com/hattedsquirrel/ryzen_monitor.git 
        du -hs ryzen_monitor 
        pwd 

    - name: Create build directory
      run: |
        rm -rf build
        mkdir build
        du -hs build

#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Configure CMake
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -S example/143_ryzen_monitor/source01 -B build -G Ninja -DDEP_DIR=`pwd` -DCMAKE_BUILD_TYPE=Release  -DGLFW_BUILD_WAYLAND=OFF

    - name: Build with Ninja
      run: ninja -C build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ryzen_mon_glgui_artifact1
        path: build/ryzen_mon_glgui